import Foundation

struct Word: Identifiable, Equatable, Hashable {
    let id: String
    let emoji: String
    let thai: String
    let romanization: String
    let english: String
    let french: String
    let category: String

    /// Retourne le texte dans la langue courante (anglais ou français)
    var localizedText: String {
        let locale = Locale.preferredLanguages.first ?? "en"
        if locale.hasPrefix("fr") {
            return french
        } else {
            return english
        }
    }
}

private func hexToEmoji(_ hex: String) -> String {
    let parts = hex.components(separatedBy: "-")
    var scalars = [Unicode.Scalar]()
    for part in parts {
        if let value = UInt32(part, radix: 16), let scalar = Unicode.Scalar(value) {
            scalars.append(scalar)
        }
    }
    return String(String.UnicodeScalarView(scalars))
}

let ALL_WORDS: [Word] = {
    let rawData: [(String, String, String, String, String, String, String)] = [
        ("cat", "1F431", "แมว", "maew", "cat", "chat", "animals"),
        ("dog", "1F436", "หมา", "maa", "dog", "chien", "animals"),
        ("cow", "1F42E", "วัว", "wua", "cow", "vache", "animals"),
        ("pig", "1F437", "หมู", "muu", "pig", "cochon", "animals"),
        ("rabbit", "1F430", "กระต่าย", "kratai", "rabbit", "lapin", "animals"),
        ("bear", "1F43B", "หมี", "mii", "bear", "ours", "animals"),
        ("lion", "1F981", "สิงโต", "singto", "lion", "lion", "animals"),
        ("elephant", "1F418", "ช้าง", "chang", "elephant", "éléphant", "animals"),
        ("fish", "1F41F", "ปลา", "plaa", "fish", "poisson", "animals"),
        ("bird", "1F426", "นก", "nok", "bird", "oiseau", "animals"),
        ("mouse", "1F42D", "หนู", "nuu", "mouse", "souris", "animals"),
        ("horse", "1F434", "ม้า", "maa", "horse", "cheval", "animals"),
        ("monkey", "1F435", "ลิง", "ling", "monkey", "singe", "animals"),
        ("frog", "1F438", "กบ", "kop", "frog", "grenouille", "animals"),
        ("chicken", "1F414", "ไก่", "kai", "chicken", "poulet", "animals"),
        ("duck", "1F986", "เป็ด", "ped", "duck", "canard", "animals"),
        ("penguin", "1F427", "เพนกวิน", "pengwin", "penguin", "manchot", "animals"),
        ("owl", "1F989", "นกฮูก", "nok huuk", "owl", "hibou", "animals"),
        ("bee", "1F41D", "ผึ้ง", "pheung", "bee", "abeille", "animals"),
        ("butterfly", "1F98B", "ผีเสื้อ", "phii suea", "butterfly", "papillon", "animals"),
        ("ladybug", "1F41E", "เต่าทอง", "tao thong", "ladybug", "coccinelle", "animals"),
        ("snail", "1F40C", "หอยทาก", "hoi thaak", "snail", "escargot", "animals"),
        ("turtle", "1F422", "เต่า", "tao", "turtle", "tortue", "animals"),
        ("snake", "1F40D", "งู", "nguu", "snake", "serpent", "animals"),
        ("crocodile", "1F40A", "จระเข้", "chorakhe", "crocodile", "crocodile", "animals"),
        ("whale", "1F433", "ปลาวาฬ", "plaa waan", "whale", "baleine", "animals"),
        ("dolphin", "1F42C", "โลมา", "looma", "dolphin", "dauphin", "animals"),
        ("shark", "1F988", "ฉลาม", "chalaam", "shark", "requin", "animals"),
        ("octopus", "1F419", "หมึก", "muek", "octopus", "pieuvre", "animals"),
        ("crab", "1F980", "ปู", "puu", "crab", "crabe", "animals"),
        ("shrimp", "1F990", "กุ้ง", "kung", "shrimp", "crevette", "animals"),
        ("tiger", "1F405", "เสือ", "suea", "tiger", "tigre", "animals"),
        ("giraffe", "1F992", "ยีราฟ", "yiraaf", "giraffe", "girafe", "animals"),
        ("zebra", "1F993", "ม้าลาย", "maa laai", "zebra", "zèbre", "animals"),
        ("panda", "1F43C", "แพนด้า", "phaendaa", "panda", "panda", "animals"),
        ("koala", "1F428", "โคอาลา", "khoo aalaa", "koala", "koala", "animals"),
        ("hamster", "1F439", "หนูแฮมสเตอร์", "nuu haem", "hamster", "hamster", "animals"),
        ("fox", "1F98A", "จิ้งจอก", "chingchok", "fox", "renard", "animals"),
        ("wolf", "1F43A", "หมาป่า", "maa paa", "wolf", "loup", "animals"),
        ("deer", "1F98C", "กวาง", "kwaang", "deer", "cerf", "animals"),
        ("goat", "1F410", "แพะ", "phae", "goat", "chèvre", "animals"),
        ("sheep", "1F411", "แกะ", "kae", "sheep", "mouton", "animals"),
        ("dragon", "1F409", "มังกร", "mangkon", "dragon", "dragon", "animals"),
        ("unicorn", "1F984", "ยูนิคอร์น", "yunikhon", "unicorn", "licorne", "animals"),
        ("apple", "1F34E", "แอปเปิ้ล", "aeppoen", "apple", "pomme", "fruits"),
        ("banana", "1F34C", "กล้วย", "kluay", "banana", "banane", "fruits"),
        ("grapes_green", "1F347", "องุ่นเขียว", "angun khiao", "green grapes", "raisins verts", "fruits"),
        ("melon_slice", "1F348", "เมลอนชิ้น", "meelon chin", "melon slice", "tranche de melon", "fruits"),
        ("banana_bunch", "1F34C", "กล้วยหอม", "kluay hom", "banana bunch", "régime de bananes", "fruits"),
        ("red_apple", "1F34E", "แอปเปิ้ลแดง", "aeppoen daeng", "red apple", "pomme rouge", "fruits"),
        ("lemon_slice", "1F34B", "มะนาวฝาน", "manao faan", "lemon slice", "tranche de citron", "fruits"),
        ("pomegranate", "1F4A3", "ทับทิม", "thapthim", "pomegranate", "grenade", "fruits"),
        ("olive", "1FAD2", "มะกอก", "makok", "olive", "olive", "fruits"),
        ("fig", "1FAD3", "มะเดื่อ", "maduea", "fig", "figue", "fruits"),
        ("chestnut", "1F330", "เกาลัด", "kaolat", "chestnut", "châtaigne", "fruits"),
        ("leafy_2", "1F96C", "ผักกาดหอม", "phak kat hom", "lettuce", "laitue", "vegetables"),
        ("broccoli_2", "1F966", "บร็อคโคลีสด", "brokkholii sot", "fresh broccoli", "brocoli frais", "vegetables"),
        ("mushroom_2", "1F344", "เห็ดหอม", "het hom", "shiitake", "shiitaké", "vegetables"),
        ("chili", "1F336", "พริกแดง", "phrik daeng", "chili pepper", "piment", "vegetables"),
        ("ginger", "1FAD4", "ขิง", "khing", "ginger", "gingembre", "vegetables"),
        ("leek", "1F96C", "ต้นกระเทียม", "ton krathiam", "leek", "poireau", "vegetables"),
        ("flatbread", "1F956", "แผ่นแป้ง", "phaen paeng", "flatbread", "pain plat", "food"),
        ("tamale", "1FAD4", "ทามาเล่", "thaamaalee", "tamale", "tamale", "food"),
        ("falafel", "1F959", "ฟาลาเฟล", "faalaafel", "falafel", "falafel", "food"),
        ("fondue_2", "1FAD5", "ฟองดูชีส", "fongduu chiis", "cheese fondue", "fondue au fromage", "food"),
        ("stuffed_flatbread", "1FAD6", "แป้งยัดไส้", "paeng yat sai", "stuffed flatbread", "pain farci", "food"),
        ("egg_fried", "1F373", "ไข่ดาว", "khai dao", "fried egg", "œuf frit", "food"),
        ("egg_boiled", "1F95A", "ไข่ต้ม", "khai tom", "boiled egg", "oeuf dur", "food"),
        ("hot_pot", "1F372", "หม้อไฟ", "mo fai", "hot pot", "fondue", "food"),
        ("bento", "1F371", "เบนโตะ", "bentoo", "bento box", "boîte bento", "food"),
        ("soft_serve", "1F366", "ซอฟต์เสิร์ฟ", "soft soep", "soft serve", "doux serve", "food"),
        ("custard", "1F36E", "พุดดิ้ง", "phut-ding", "custard", "crème", "food"),
        ("candy_2", "1F36C", "ลูกกวาด", "luk kwaat", "hard candy", "dur bonbon", "food"),
        ("chocolate_bar", "1F36B", "ช็อกโกแลตแท่ง", "chok-ko-laet thaeng", "chocolate bar", "chocolat bar", "food"),
        ("teapot", "1F375", "กาน้ำชา", "kaa nam chaa", "teapot", "théière", "drinks"),
        ("tea_cup", "1F375", "ถ้วยชา", "thuai chaa", "tea cup", "thé cup", "drinks"),
        ("coffee_mug", "2615", "แก้วกาแฟ", "kaeo kaafae", "coffee mug", "café mug", "drinks"),
        ("beverage_can", "1F964", "กระป๋องเครื่องดื่ม", "krapong khrueang duem", "beverage can", "canette de boisson", "drinks"),
        ("juice_box", "1F9C3", "กล่องน้ำผลไม้", "klong nam phonlamai", "juice box", "jus box", "drinks"),
        ("glass_milk", "1F95B", "แก้วนม", "kaeo nom", "glass of milk", "glass of lait", "drinks"),
        ("wine_glass", "1F377", "แก้วไวน์", "kaeo wai", "wine glass", "verre à vin", "drinks"),
        ("beer_mug", "1F37A", "แก้วเบียร์", "kaeo bia", "beer mug", "chope de bière", "drinks"),
        ("cocktail_glass", "1F378", "แก้วค็อกเทล", "kaeo khokthen", "cocktail glass", "verre à cocktail", "drinks"),
        ("mate", "1F9C9", "ชามาเต", "chaa maatee", "mate", "maté", "drinks"),
        ("ice", "1F9CA", "น้ำแข็งหลอด", "nam khaeng lot", "ice cubes", "glaçons", "drinks"),
        ("sugar", "1F9C2", "น้ำตาล", "nam taan", "sugar", "sucre", "food"),
        ("pepper_shaker", "1F9C2", "พริกไทย", "phrik thai", "pepper", "poivron", "food"),
        ("olive_oil", "1FAD2", "น้ำมันมะกอก", "nam man makok", "olive oil", "huile d'olive", "food"),
        ("garlic_2", "1F9C4", "หัวกระเทียม", "hua krathiam", "garlic bulb", "garlic ampoule", "vegetables"),
        ("onion_2", "1F9C5", "หอมหัวใหญ่", "hom hua yai", "large onion", "gros oignon", "vegetables"),
        ("potato_2", "1F954", "มันฝรั่งสด", "man farang sot", "fresh potato", "fresh pomme de terre", "vegetables"),
        ("corn_2", "1F33D", "ฝักข้าวโพด", "fak khao phot", "corn on the cob", "maïs on the cob", "vegetables"),
        ("orange", "1F34A", "ส้ม", "som", "orange", "orange", "fruits"),
        ("strawberry", "1F353", "สตรอว์เบอร์รี", "satroboerri", "strawberry", "fraise", "fruits"),
        ("watermelon", "1F349", "แตงโม", "taengmoo", "watermelon", "pastèque", "fruits"),
        ("pineapple", "1F34D", "สับปะรด", "sapparot", "pineapple", "ananas", "fruits"),
        ("cherries", "1F352", "เชอร์รี่", "choerri", "cherries", "cerises", "fruits"),
        ("peach", "1F351", "ลูกพีช", "luuk phiich", "peach", "pêche", "fruits"),
        ("pear", "1F350", "ลูกแพร์", "luuk phae", "pear", "poire", "fruits"),
        ("lemon", "1F34B", "มะนาว", "manao", "lemon", "citron", "fruits"),
        ("mango", "1F96D", "มะม่วง", "mamuang", "mango", "mangue", "fruits"),
        ("coconut", "1F965", "มะพร้าว", "maphrao", "coconut", "noix de coco", "fruits"),
        ("avocado", "1F951", "อะโวคาโด", "awokhaado", "avocado", "avocat", "fruits"),
        ("kiwi", "1F95D", "กีวี", "kiiwii", "kiwi", "kiwi", "fruits"),
        ("melon", "1F348", "เมล่อน", "meelon", "melon", "melon", "fruits"),
        ("carrot", "1F955", "แครอท", "khaerot", "carrot", "carotte", "vegetables"),
        ("tomato", "1F345", "มะเขือเทศ", "makhuea thet", "tomato", "tomate", "vegetables"),
        ("corn", "1F33D", "ข้าวโพด", "khao phot", "corn", "maïs", "vegetables"),
        ("mushroom", "1F344", "เห็ด", "het", "mushroom", "champignon", "vegetables"),
        ("eggplant", "1F346", "มะเขือม่วง", "makhuea muang", "eggplant", "aubergine", "vegetables"),
        ("pepper", "1F336", "พริก", "phrik", "pepper", "poivron", "vegetables"),
        ("cucumber", "1F952", "แตงกวา", "taeng kwa", "cucumber", "concombre", "vegetables"),
        ("broccoli", "1F966", "บร็อคโคลี", "brokkholii", "broccoli", "brocoli", "vegetables"),
        ("onion", "1F9C5", "หัวหอม", "hua hom", "onion", "oignon", "vegetables"),
        ("garlic", "1F9C4", "กระเทียม", "krathiam", "garlic", "ail", "vegetables"),
        ("peanut", "1F95C", "ถั่วลิสง", "thua lisong", "peanut", "cacahuète", "vegetables"),
        ("bread", "1F35E", "ขนมปัง", "khanom pang", "bread", "pain", "food"),
        ("rice", "1F35A", "ข้าว", "khao", "rice", "riz", "food"),
        ("noodles", "1F35C", "ก๋วยเตี๋ยว", "kuai tiao", "noodles", "nouilles", "food"),
        ("sushi", "1F363", "ซูชิ", "suuchi", "sushi", "sushi", "food"),
        ("pizza", "1F355", "พิซซ่า", "phitsa", "pizza", "pizza", "food"),
        ("hamburger", "1F354", "แฮมเบอร์เกอร์", "haemboekoer", "hamburger", "hamburger", "food"),
        ("fries", "1F35F", "เฟรนช์ฟรายส์", "frenchfraais", "fries", "frites", "food"),
        ("hotdog", "1F32D", "ฮอทดอก", "hot dok", "hotdog", "hotdog", "food"),
        ("egg", "1F95A", "ไข่", "khai", "egg", "oeuf", "food"),
        ("cheese", "1F9C0", "ชีส", "chiis", "cheese", "fromage", "food"),
        ("cake", "1F370", "เค้ก", "khek", "cake", "gâteau", "food"),
        ("cookie", "1F36A", "คุกกี้", "khukkii", "cookie", "biscuit", "food"),
        ("icecream", "1F368", "ไอศกรีม", "aisakriim", "ice cream", "glace", "food"),
        ("chocolate", "1F36B", "ช็อกโกแลต", "chokkoolaet", "chocolate", "chocolat", "food"),
        ("candy", "1F36C", "ลูกอม", "luuk om", "candy", "bonbon", "food"),
        ("donut", "1F369", "โดนัท", "doonat", "donut", "beignet", "food"),
        ("lollipop", "1F36D", "อมยิ้ม", "om yim", "lollipop", "lollipop", "food"),
        ("water", "1F4A7", "น้ำ", "nam", "water", "eau", "drinks"),
        ("milk", "1F95B", "นม", "nom", "milk", "lait", "drinks"),
        ("juice", "1F9C3", "น้ำผลไม้", "nam phonlamai", "juice", "jus", "drinks"),
        ("tea", "1F375", "ชา", "chaa", "tea", "thé", "drinks"),
        ("coffee", "2615", "กาแฟ", "kaafae", "coffee", "café", "drinks"),
        ("car", "1F697", "รถ", "rot", "car", "voiture", "transport"),
        ("bus", "1F68C", "รถบัส", "rot bas", "bus", "autobus", "transport"),
        ("train", "1F682", "รถไฟ", "rot fai", "train", "train", "transport"),
        ("plane", "2708", "เครื่องบิน", "khruang bin", "plane", "avion", "transport"),
        ("boat", "26F5", "เรือ", "ruea", "boat", "bateau", "transport"),
        ("bike", "1F6B2", "จักรยาน", "chakrayaan", "bike", "vélo", "transport"),
        ("motorbike", "1F3CD", "มอเตอร์ไซค์", "motoesai", "motorbike", "motocyclette", "transport"),
        ("truck", "1F69A", "รถบรรทุก", "rot banthuk", "truck", "camion", "transport"),
        ("taxi", "1F695", "แท็กซี่", "thaeksi", "taxi", "taxi", "transport"),
        ("police", "1F693", "รถตำรวจ", "rot tamruat", "police car", "voiture de police", "transport"),
        ("ambulance", "1F691", "รถพยาบาล", "rot phayabaan", "ambulance", "ambulance", "transport"),
        ("tractor", "1F69C", "รถแทรกเตอร์", "rot traektoe", "tractor", "tracteur", "transport"),
        ("rocket", "1F680", "จรวด", "charuat", "rocket", "fusée", "transport"),
        ("helicopter", "1F681", "เฮลิคอปเตอร์", "heelikhoptoe", "helicopter", "hélicoptère", "transport"),
        ("house", "1F3E0", "บ้าน", "baan", "house", "maison", "home"),
        ("chair", "1FA91", "เก้าอี้", "kao ii", "chair", "chaise", "home"),
        ("bed", "1F6CF", "เตียง", "tiang", "bed", "lit", "home"),
        ("bathtub", "1F6C1", "อ่างอาบน้ำ", "aang aap nam", "bathtub", "baignoire", "home"),
        ("toilet", "1F6BD", "ห้องน้ำ", "hong nam", "toilet", "toilettes", "home"),
        ("phone", "1F4F1", "โทรศัพท์", "thoorasap", "phone", "téléphone", "home"),
        ("tv", "1F4FA", "โทรทัศน์", "thoorathat", "TV", "TV", "home"),
        ("computer", "1F4BB", "คอมพิวเตอร์", "khomphiutoe", "computer", "ordinateur", "home"),
        ("clock", "23F0", "นาฬิกา", "naalikaa", "clock", "horloge", "home"),
        ("key", "1F511", "กุญแจ", "kunchae", "key", "clé", "home"),
        ("bulb", "1F4A1", "หลอดไฟ", "lot fai", "light bulb", "ampoule", "home"),
        ("scissors", "2702", "กรรไกร", "kankrai", "scissors", "ciseaux", "home"),
        ("book", "1F4D6", "หนังสือ", "nangsue", "book", "livre", "home"),
        ("pencil", "270F", "ดินสอ", "dinso", "pencil", "crayon", "home"),
        ("backpack", "1F392", "กระเป๋า", "krapao", "backpack", "sac à dos", "home"),
        ("spoon", "1F944", "ช้อน", "chon", "spoon", "cuillère", "home"),
        ("fork", "1F374", "ส้อม", "som", "fork", "fourchette", "home"),
        ("teddy", "1F9F8", "ตุ๊กตาหมี", "tukkata mii", "teddy bear", "teddy ours", "toys"),
        ("balloon", "1F388", "ลูกโป่ง", "luuk pong", "balloon", "ballon", "toys"),
        ("kite", "1FA81", "ว่าว", "waao", "kite", "kite", "toys"),
        ("yoyo", "1FA80", "โยโย่", "yooyoo", "yoyo", "yoyo", "toys"),
        ("soccer", "26BD", "ลูกฟุตบอล", "luuk futbon", "soccer ball", "soccer ballon", "toys"),
        ("basketball", "1F3C0", "ลูกบาส", "luuk baas", "basketball", "basketball", "toys"),
        ("puzzle", "1F9E9", "จิ๊กซอว์", "chiksow", "puzzle", "puzzle", "toys"),
        ("shirt", "1F455", "เสื้อ", "suea", "shirt", "chemise", "clothes"),
        ("pants", "1F456", "กางเกง", "kangkeng", "pants", "pantalon", "clothes"),
        ("dress", "1F457", "ชุดเดรส", "chut dres", "dress", "robe", "clothes"),
        ("socks", "1F9E6", "ถุงเท้า", "thung thao", "socks", "socks", "clothes"),
        ("shoe", "1F45F", "รองเท้า", "rong thao", "shoe", "chaussure", "clothes"),
        ("hat", "1F3A9", "หมวก", "muak", "hat", "chapeau", "clothes"),
        ("glasses", "1F453", "แว่นตา", "waen taa", "glasses", "glasses", "clothes"),
        ("umbrella", "2602", "ร่ม", "rom", "umbrella", "umbrella", "clothes"),
        ("gloves", "1F9E4", "ถุงมือ", "thung mue", "gloves", "gloves", "clothes"),
        ("scarf", "1F9E3", "ผ้าพันคอ", "phaa phan khaw", "scarf", "écharpe", "clothes"),
        ("crown", "1F451", "มงกุฎ", "mongkut", "crown", "crown", "clothes"),
        ("ring", "1F48D", "แหวน", "waen", "ring", "ring", "clothes"),
        ("sun", "2600", "พระอาทิตย์", "phra aathit", "sun", "soleil", "nature"),
        ("moon", "1F319", "พระจันทร์", "phra chan", "moon", "lune", "nature"),
        ("star", "2B50", "ดาว", "daao", "star", "étoile", "nature"),
        ("cloud", "2601", "เมฆ", "meek", "cloud", "nuage", "nature"),
        ("rain", "1F327", "ฝน", "fon", "rain", "pluie", "nature"),
        ("snowflake", "2744", "หิมะ", "himaa", "snow", "neige", "nature"),
        ("rainbow", "1F308", "รุ้ง", "rung", "rainbow", "arc-en-ciel", "nature"),
        ("flower", "1F33C", "ดอกไม้", "dok mai", "flower", "fleur", "nature"),
        ("tulip", "1F337", "ดอกทิวลิป", "dok thiwlip", "tulip", "tulipe", "nature"),
        ("rose", "1F339", "ดอกกุหลาบ", "dok kulaap", "rose", "rose", "nature"),
        ("tree", "1F333", "ต้นไม้", "ton mai", "tree", "arbre", "nature"),
        ("leaf", "1F343", "ใบไม้", "bai mai", "leaf", "feuille", "nature"),
        ("fire", "1F525", "ไฟ", "fai", "fire", "feu", "nature"),
        ("mountain", "26F0", "ภูเขา", "phuukhao", "mountain", "montagne", "nature"),
        ("earth", "1F30D", "โลก", "lok", "earth", "earth", "nature"),
        ("cactus", "1F335", "กระบองเพชร", "krabong phet", "cactus", "cactus", "nature"),
        ("eye", "1F441", "ตา", "taa", "eye", "oeil", "body"),
        ("ear", "1F442", "หู", "huu", "ear", "oreille", "body"),
        ("nose", "1F443", "จมูก", "chamuuk", "nose", "nez", "body"),
        ("mouth", "1F444", "ปาก", "paak", "mouth", "bouche", "body"),
        ("tongue", "1F445", "ลิ้น", "lin", "tongue", "langue", "body"),
        ("hand", "270B", "มือ", "mue", "hand", "main", "body"),
        ("foot", "1F9B6", "เท้า", "thao", "foot", "pied", "body"),
        ("tooth", "1F9B7", "ฟัน", "fan", "tooth", "dent", "body"),
        ("brain", "1F9E0", "สมอง", "samong", "brain", "cerveau", "body"),
        ("leg", "1F9B5", "ขา", "khaa", "leg", "jambe", "body"),
        ("guitar", "1F3B8", "กีตาร์", "kiitaa", "guitar", "guitare", "music"),
        ("piano", "1F3B9", "เปียโน", "piaanoo", "piano", "piano", "music"),
        ("trumpet", "1F3BA", "ทรัมเป็ต", "thrampet", "trumpet", "trompette", "music"),
        ("violin", "1F3BB", "ไวโอลิน", "waioolin", "violin", "violon", "music"),
        ("drum", "1F941", "กลอง", "klong", "drum", "tambour", "music"),
        ("saxophone", "1F3B7", "แซกโซโฟน", "saeksoofoon", "saxophone", "saxophone", "music"),
        ("microphone", "1F3A4", "ไมโครโฟน", "maikhroofoon", "microphone", "microphone", "music"),
        ("happy", "1F600", "ยิ้ม", "yim", "happy", "heureux", "feelings"),
        ("laugh", "1F602", "หัวเราะ", "huaro", "laugh", "rire", "feelings"),
        ("love", "1F60D", "รัก", "rak", "love", "amour", "feelings"),
        ("cry", "1F622", "ร้องไห้", "rong hai", "cry", "pleurer", "feelings"),
        ("angry", "1F620", "โกรธ", "krot", "angry", "en colère", "feelings"),
        ("surprised", "1F62E", "ตกใจ", "tokchai", "surprised", "surprised", "feelings"),
        ("sleepy", "1F634", "ง่วงนอน", "nguang non", "sleepy", "sleepy", "feelings"),
        ("cool", "1F60E", "เท่ห์", "thee", "cool", "frais", "feelings"),
        ("sick", "1F912", "ป่วย", "puai", "sick", "malade", "feelings"),
        ("kiss", "1F618", "จูบ", "chup", "kiss", "baiser", "feelings"),
        ("heart", "2764", "หัวใจ", "huachai", "heart", "cœur", "feelings"),
        ("party", "1F389", "ปาร์ตี้", "paatii", "party", "fête", "feelings"),
        ("num1", "0031-FE0F-20E3", "หนึ่ง", "neung", "one", "un", "numbers"),
        ("num2", "0032-FE0F-20E3", "สอง", "song", "two", "deux", "numbers"),
        ("num3", "0033-FE0F-20E3", "สาม", "saam", "three", "trois", "numbers"),
        ("num4", "0034-FE0F-20E3", "สี่", "sii", "four", "quatre", "numbers"),
        ("num5", "0035-FE0F-20E3", "ห้า", "haa", "five", "cinq", "numbers"),
        ("num6", "0036-FE0F-20E3", "หก", "hok", "six", "six", "numbers"),
        ("num7", "0037-FE0F-20E3", "เจ็ด", "jet", "seven", "sept", "numbers"),
        ("num8", "0038-FE0F-20E3", "แปด", "paet", "eight", "huit", "numbers"),
        ("num9", "0039-FE0F-20E3", "เก้า", "kao", "nine", "neuf", "numbers"),
        ("num10", "1F51F", "สิบ", "sip", "ten", "dix", "numbers"),
        ("c_red", "1F534", "สีแดง", "sii daeng", "red", "rouge", "colors"),
        ("c_orange", "1F7E0", "สีส้ม", "sii som", "orange", "orange", "colors"),
        ("c_yellow", "1F7E1", "สีเหลือง", "sii lueang", "yellow", "jaune", "colors"),
        ("c_green", "1F7E2", "สีเขียว", "sii khiao", "green", "vert", "colors"),
        ("c_blue", "1F535", "สีน้ำเงิน", "sii nam ngoen", "blue", "bleu", "colors"),
        ("c_purple", "1F7E3", "สีม่วง", "sii muang", "purple", "violet", "colors"),
        ("c_brown", "1F7E4", "สีน้ำตาล", "sii nam taan", "brown", "marron", "colors"),
        ("c_black", "26AB", "สีดำ", "sii dam", "black", "noir", "colors"),
        ("c_white", "26AA", "สีขาว", "sii khaow", "white", "blanc", "colors"),
        ("leopard", "1F406", "เสือดาว", "suea daao", "leopard", "léopard", "animals"),
        ("rhino", "1F98F", "แรด", "raet", "rhino", "rhino", "animals"),
        ("camel", "1F42A", "อูฐ", "uut", "camel", "chameau", "animals"),
        ("kangaroo", "1F998", "จิงโจ้", "chingcho", "kangaroo", "kangaroo", "animals"),
        ("boar", "1F417", "หมูป่า", "muu paa", "boar", "sanglier", "animals"),
        ("squirrel", "1F43F", "กระรอก", "krarok", "squirrel", "écureuil", "animals"),
        ("rooster", "1F413", "ไก่ตัวผู้", "kai tua phu", "rooster", "rooster", "animals"),
        ("eagle", "1F985", "นกอินทรี", "nok insi", "eagle", "aigle", "animals"),
        ("peacock", "1F99A", "นกยูง", "nok yung", "peacock", "peacock", "animals"),
        ("parrot", "1F99C", "นกแก้ว", "nok kaeo", "parrot", "perroquet", "animals"),
        ("flamingo", "1F9A9", "ฟลามิงโก", "flamingkho", "flamingo", "flamingo", "animals"),
        ("turkey", "1F983", "ไก่งวง", "kai nguang", "turkey", "turkey", "animals"),
        ("hedgehog", "1F994", "เม่น", "men", "hedgehog", "hérisson", "animals"),
        ("sloth", "1F9A5", "สลอธ", "saloth", "sloth", "sloth", "animals"),
        ("otter", "1F9A6", "นาก", "naak", "otter", "loutre", "animals"),
        ("trex", "1F996", "ไดโนเสาร์", "dainosao", "T-Rex", "T-Rex", "animals"),
        ("lizard", "1F98E", "ตุ๊กแก", "tukkae", "lizard", "lézard", "animals"),
        ("beetle", "1FAB2", "ด้วง", "duang", "beetle", "scarabée", "animals"),
        ("worm", "1FAB1", "หนอน", "non", "worm", "worm", "animals"),
        ("spider", "1F577", "แมงมุม", "maengmum", "spider", "araignée", "animals"),
        ("ant", "1F41C", "มด", "mot", "ant", "fourmi", "animals"),
        ("mosquito", "1F99F", "ยุง", "yung", "mosquito", "mosquito", "animals"),
        ("scorpion", "1F982", "แมงป่อง", "maengpong", "scorpion", "scorpion", "animals"),
        ("beaver", "1F9AB", "บีเวอร์", "biiwoe", "beaver", "castor", "animals"),
        ("skunk", "1F9A8", "สกั๊งก์", "sakang", "skunk", "skunk", "animals"),
        ("swan", "1F9A2", "หงส์", "hong", "swan", "cygne", "animals"),
        ("microbe", "1F9A0", "เชื้อโรค", "chuea rok", "microbe", "microbe", "animals"),
        ("paw", "1F43E", "รอยเท้าสัตว์", "roi thao sat", "paw", "paw", "animals"),
        ("feather", "1FAB6", "ขนนก", "khon nok", "feather", "feather", "animals"),
        ("monkey_face", "1F435", "หน้าลิง", "naa ling", "monkey face", "singe visage", "animals"),
        ("gorilla", "1F98D", "กอริลลา", "koorillaa", "gorilla", "gorilla", "animals"),
        ("orangutan", "1F9A7", "อุรังอุตัง", "urang-utang", "orangutan", "orangutan", "animals"),
        ("dog_face", "1F436", "หน้าหมา", "naa maa", "dog face", "chien visage", "animals"),
        ("poodle", "1F429", "หมาพุดเดิล", "maa phuddoen", "poodle", "poodle", "animals"),
        ("raccoon", "1F99D", "แรคคูน", "raekkhuun", "raccoon", "raccoon", "animals"),
        ("cat_face", "1F431", "หน้าแมว", "naa maew", "cat face", "chat visage", "animals"),
        ("tiger_face", "1F42F", "หน้าเสือ", "naa suea", "tiger face", "tigre visage", "animals"),
        ("leopard_f", "1F406", "หน้าเสือดาว", "naa suea daao", "leopard face", "léopard visage", "animals"),
        ("horse_face", "1F434", "หน้าม้า", "naa maa", "horse face", "cheval visage", "animals"),
        ("cow_face", "1F42E", "หน้าวัว", "naa wua", "cow face", "vache visage", "animals"),
        ("pig_face", "1F437", "หน้าหมู", "naa muu", "pig face", "cochon visage", "animals"),
        ("boar_face", "1F417", "หน้าหมูป่า", "naa muu paa", "boar face", "tête de sanglier", "animals"),
        ("ram", "2648", "แกะตัวผู้", "kae tua phu", "ram", "ram", "animals"),
        ("ewe", "1F411", "แกะตัวเมีย", "kae tua mia", "ewe", "ewe", "animals"),
        ("lamb", "1F411", "ลูกแกะ", "luuk kae", "lamb", "lamb", "animals"),
        ("llama", "1F999", "ลามะ", "laama", "llama", "llama", "animals"),
        ("giraffe_f", "1F992", "หน้ายีราฟ", "naa yiraaf", "giraffe face", "girafe visage", "animals"),
        ("elephant_f", "1F418", "หน้าช้าง", "naa chang", "elephant face", "éléphant visage", "animals"),
        ("rhino_f", "1F98F", "หน้าแรด", "naa raet", "rhino face", "rhino visage", "animals"),
        ("hippo_f", "1F99B", "หน้าฮิปโป", "naa hippo", "hippo face", "hippopotame visage", "animals"),
        ("mouse_face", "1F42D", "หน้าหนู", "naa nuu", "mouse face", "souris visage", "animals"),
        ("rabbit_face", "1F430", "หน้ากระต่าย", "naa kratai", "rabbit face", "lapin visage", "animals"),
        ("chipmunk", "1F43F", "กระรอกชิปมังก์", "chipmang", "chipmunk", "chipmunk", "animals"),
        ("rat", "1F400", "หนูหริ่ง", "nuu ring", "rat", "rat", "animals"),
        ("badger", "1F9A1", "แบดเจอร์", "baet-choe", "badger", "blaireau", "animals"),
        ("chicken_f", "1F414", "หน้าไก่", "naa kai", "chicken face", "poulet visage", "animals"),
        ("hatching", "1F423", "ลูกไก่ฟัก", "luuk kai fak", "hatching chick", "hatching chick", "animals"),
        ("baby_chick", "1F424", "ลูกไก่", "luuk kai", "baby chick", "poussin", "animals"),
        ("front_chick", "1F425", "ลูกไก่หันหน้า", "luuk kai han naa", "front chick", "front chick", "animals"),
        ("dove", "1F54A", "นกพิราบ", "nok phiraap", "dove", "dove", "animals"),
        ("pigeon", "1F426", "นกพิราบป่า", "nok phiraap paa", "pigeon", "pigeon", "animals"),
        ("duck_f", "1F986", "หน้าเป็ด", "naa ped", "duck face", "canard visage", "animals"),
        ("crane", "1F9A2", "นกกระเรียน", "nok krarian", "crane", "crane", "animals"),
        ("black_bird", "1F426", "นกสีดำ", "nok sii dam", "black bird", "oiseau noir", "animals"),
        ("dodo", "1F9A1", "นกโดโด้", "nok doodoo", "dodo", "dodo", "animals"),
        ("polar_bear", "1F43B", "หมีขั้วโลก", "mii khua lok", "polar bear", "polar ours", "animals"),
        ("brown_bear", "1F43B", "หมีสีน้ำตาล", "mii sii nam taan", "brown bear", "ours brun", "animals"),
        ("lizard_2", "1F98E", "จิ้งจก", "ching chok", "house lizard", "maison lézard", "animals"),
        ("chameleon", "1F98E", "กิ้งก่าเปลี่ยนสี", "kingkaa plian sii", "chameleon", "chameleon", "animals"),
        ("frog_f", "1F438", "หน้ากบ", "naa kop", "frog face", "grenouille visage", "animals"),
        ("shrimp_2", "1F990", "กุ้งแม่น้ำ", "kung mae nam", "river shrimp", "crevette", "sea"),
        ("lobster", "1F99E", "กุ้งมังกร", "kung mangkon", "lobster", "homard", "sea"),
        ("squid", "1F991", "ปลาหมึกกล้วย", "plaa muek kluay", "squid", "squid", "sea"),
        ("oyster", "1F9AA", "หอยนางรม", "hoi naang rom", "oyster", "huître", "sea"),
        ("shell", "1F41A", "เปลือกหอย", "plueak hoi", "shell", "shell", "sea"),
        ("coral", "1FAB8", "ปะการัง", "pakaarang", "coral", "corail", "sea"),
        ("jellyfish", "1FABC", "แมงกะพรุน", "maeng kaprun", "jellyfish", "jellyfish", "sea"),
        ("seal", "1F9AD", "แมวน้ำ", "maew nam", "seal", "seal", "sea"),
        ("tropical_fish", "1F420", "ปลาเขตร้อน", "plaa khet ron", "tropical fish", "tropical poisson", "sea"),
        ("blowfish", "1F421", "ปลาปักเป้า", "plaa pak pao", "blowfish", "poisson-globe", "sea"),
        ("fish_2", "1F41F", "ปลาตัวเล็ก", "plaa tua lek", "small fish", "petit poisson", "sea"),
        ("shark_f", "1F988", "ครีบฉลาม", "khrip chalaam", "shark fin", "requin fin", "sea"),
        ("octopus_f", "1F419", "หัวปลาหมึก", "hua plaa muek", "octopus face", "pieuvre visage", "sea"),
        ("whale_2", "1F40B", "วาฬหลังค่อม", "waan lang khom", "humpback whale", "humpback baleine", "sea"),
        ("spouting_whale", "1F433", "วาฬพ่นน้ำ", "waan phon nam", "spouting whale", "spouting baleine", "sea"),
        ("sea_turtle", "1F422", "เต่าทะเล", "tao thale", "sea turtle", "sea tortue", "sea"),
        ("crab_f", "1F980", "ก้ามปู", "kaam puu", "crab claw", "crabe claw", "sea"),
        ("green_apple", "1F34F", "แอปเปิ้ลเขียว", "aeppoen khiao", "green apple", "pomme verte", "fruits"),
        ("blueberry", "1FAD0", "บลูเบอร์รี่", "bluuboerri", "blueberry", "myrtille", "fruits"),
        ("tangerine", "1F34A", "ส้มเขียวหวาน", "som khiao waan", "tangerine", "tangerine", "fruits"),
        ("peas", "1FADB", "ถั่วลันเตา", "thua lantao", "peas", "pois", "vegetables"),
        ("bell_pepper", "1FAD1", "พริกหวาน", "phrik waan", "bell pepper", "poivron", "vegetables"),
        ("croissant", "1F950", "ครัวซองต์", "khruasong", "croissant", "croissant", "food"),
        ("baguette", "1F956", "บาแกตต์", "baaket", "baguette", "baguette", "food"),
        ("pretzel", "1F968", "เพรทเซล", "phretsel", "pretzel", "pretzel", "food"),
        ("bagel", "1F96F", "เบเกิล", "beeken", "bagel", "bagel", "food"),
        ("pancakes", "1F95E", "แพนเค้ก", "phankek", "pancakes", "crêpes", "food"),
        ("waffle", "1F9C7", "วาฟเฟิล", "wafflen", "waffle", "gaufre", "food"),
        ("taco", "1F32E", "ทาโก้", "taakoo", "taco", "taco", "food"),
        ("burrito", "1F32F", "เบอร์ริโต", "boeriito", "burrito", "burrito", "food"),
        ("sandwich", "1F96A", "แซนด์วิช", "saendwich", "sandwich", "sandwich", "food"),
        ("curry", "1F35B", "แกง", "kaeng", "curry", "curry", "food"),
        ("spaghetti", "1F35D", "สปาเกตตี้", "sapaaketti", "spaghetti", "spaghetti", "food"),
        ("ramen", "1F35C", "ราเมน", "raamen", "ramen", "ramen", "food"),
        ("stew", "1F372", "สตูว์", "satuu", "stew", "stew", "food"),
        ("bowl_food", "1F963", "ชามอาหาร", "chaam aahaan", "bowl", "bol", "food"),
        ("salad", "1F957", "สลัด", "salat", "salad", "salade", "food"),
        ("popcorn", "1F37F", "ป๊อปคอร์น", "poppkhon", "popcorn", "pop-corn", "food"),
        ("butter", "1F9C8", "เนย", "noei", "butter", "beurre", "food"),
        ("honey", "1F36F", "น้ำผึ้ง", "nam pheung", "honey", "miel", "food"),
        ("cupcake", "1F9C1", "คัพเค้ก", "khap khek", "cupcake", "cupcake", "food"),
        ("shortcake", "1F370", "ช็อตเค้ก", "chot khek", "shortcake", "shortcake", "food"),
        ("pie", "1F967", "พาย", "paai", "pie", "pie", "food"),
        ("meat", "1F356", "เนื้อ", "nuea", "meat", "viande", "food"),
        ("chicken_leg", "1F357", "ขาไก่", "khaa kai", "chicken leg", "poulet jambe", "food"),
        ("bacon", "1F953", "เบคอน", "bekhon", "bacon", "bacon", "food"),
        ("soup", "1F35C", "ซุป", "sup", "soup", "soupe", "food"),
        ("wine", "1F377", "ไวน์", "wai", "wine", "vin", "drinks"),
        ("beer", "1F37A", "เบียร์", "bia", "beer", "bière", "drinks"),
        ("cocktail", "1F378", "ค็อกเทล", "khokthen", "cocktail", "cocktail", "drinks"),
        ("ice_cube", "1F9CA", "น้ำแข็ง", "nam khaeng", "ice cube", "ice cube", "drinks"),
        ("baby_bottle", "1F37C", "ขวดนม", "khuat nom", "baby bottle", "biberon", "drinks"),
        ("sailboat", "26F5", "เรือใบ", "ruea bai", "sailboat", "sailboat", "transport"),
        ("ship", "1F6A2", "เรือใหญ่", "ruea yai", "ship", "ship", "transport"),
        ("speedboat", "1F6A4", "เรือเร็ว", "ruea reo", "speedboat", "speedboat", "transport"),
        ("canoe", "1F6F6", "เรือแคนู", "ruea khanu", "canoe", "canoe", "transport"),
        ("ufo", "1F6F8", "ยูเอฟโอ", "yuu ef oo", "UFO", "OVNI", "transport"),
        ("skateboard", "1F6F9", "สเก็ตบอร์ด", "saket bot", "skateboard", "skateboard", "transport"),
        ("subway", "1F687", "รถไฟใต้ดิน", "rot fai tai din", "subway", "subway", "transport"),
        ("train_fast", "1F684", "รถไฟความเร็วสูง", "rot fai khwam reo sung", "high-speed train", "high-speed train", "transport"),
        ("tram", "1F68B", "รถราง", "rot raang", "tram", "tram", "transport"),
        ("door", "1F6AA", "ประตู", "pratuu", "door", "porte", "home"),
        ("window", "1FA9F", "หน้าต่าง", "naa taang", "window", "fenêtre", "home"),
        ("couch", "1F6CB", "โซฟา", "soofaa", "couch", "couch", "home"),
        ("mirror", "1FA9E", "กระจก", "krachok", "mirror", "miroir", "home"),
        ("shower", "1F6BF", "ฝักบัว", "fakbua", "shower", "shower", "home"),
        ("broom", "1F9F9", "ไม้กวาด", "mai kwaat", "broom", "balai", "home"),
        ("basket", "1F9FA", "ตะกร้า", "takraa", "basket", "panier", "home"),
        ("soap", "1F9FC", "สบู่", "sabuu", "soap", "savon", "home"),
        ("sponge", "1F9FD", "ฟองน้ำ", "fong nam", "sponge", "sponge", "home"),
        ("bell", "1F514", "กระดิ่ง", "kradeng", "bell", "cloche", "home"),
        ("bucket", "1FAA3", "ถัง", "thang", "bucket", "seau", "home"),
        ("plate", "1F37D", "จาน", "chaan", "plate", "assiette", "home"),
        ("knife", "1F52A", "มีด", "miit", "knife", "couteau", "home"),
        ("cup", "1F964", "แก้ว", "kaeo", "cup", "tasse", "home"),
        ("plunger", "1FAA0", "ไม้ยาง", "mai yaang", "plunger", "plunger", "home"),
        ("chopsticks", "1F962", "ตะเกียบ", "takiap", "chopsticks", "baguettes", "home"),
        ("dice", "1F3B2", "ลูกเต๋า", "luk tao", "dice", "dice", "toys"),
        ("joystick", "1F579", "จอยสติ๊ก", "choi satik", "joystick", "joystick", "toys"),
        ("pinata", "1FA85", "พิญาต้า", "phinaataa", "piñata", "piñata", "toys"),
        ("disc", "1F94F", "จานร่อน", "chaan ron", "disc", "disc", "toys"),
        ("bow", "1F3F9", "ธนู", "thanuu", "bow", "arc", "toys"),
        ("coat", "1F9E5", "เสื้อโค้ท", "suea khoot", "coat", "manteau", "clothes"),
        ("kimono", "1F458", "กิโมโน", "kimono", "kimono", "kimono", "clothes"),
        ("sari", "1F97B", "ส่าหรี", "saarii", "sari", "sari", "clothes"),
        ("boot", "1F462", "รองเท้าบูต", "rongthao buut", "boots", "bottes", "clothes"),
        ("cap", "1F9E2", "หมวกแก๊ป", "muak kaep", "cap", "casquette", "clothes"),
        ("necktie", "1F454", "เนกไท", "nekthai", "necktie", "necktie", "clothes"),
        ("gem", "1F48E", "เพชร", "phet", "gem", "gem", "clothes"),
        ("wave", "1F30A", "คลื่น", "khluen", "wave", "agiter", "nature"),
        ("palm_tree", "1F334", "ต้นปาล์ม", "ton paam", "palm tree", "palm arbre", "nature"),
        ("evergreen", "1F332", "ต้นสน", "ton son", "evergreen", "evergreen", "nature"),
        ("seedling", "1F331", "ต้นกล้า", "ton klaa", "seedling", "seedling", "nature"),
        ("clover", "1F340", "โคลเวอร์", "khloowoe", "clover", "clover", "nature"),
        ("maple", "1F341", "ใบเมเปิล", "bai meepoen", "maple", "maple", "nature"),
        ("sunflower", "1F33B", "ทานตะวัน", "thaantawan", "sunflower", "tournesol", "nature"),
        ("hibiscus", "1F33A", "ชบา", "chabaa", "hibiscus", "hibiscus", "nature"),
        ("cherry_blossom", "1F338", "ซากุระ", "saakuraa", "cherry blossom", "fleur de cerisier", "nature"),
        ("bouquet", "1F490", "ช่อดอกไม้", "cho dok mai", "bouquet", "bouquet", "nature"),
        ("volcano", "1F30B", "ภูเขาไฟ", "phu khao fai", "volcano", "volcan", "nature"),
        ("beach", "1F3D6", "ชายหาด", "chai haat", "beach", "plage", "nature"),
        ("desert", "1F3DC", "ทะเลทราย", "thale saai", "desert", "désert", "nature"),
        ("droplet", "1F4A7", "หยดน้ำ", "yot nam", "droplet", "droplet", "nature"),
        ("face", "1F9D1", "หน้า", "naa", "face", "visage", "body"),
        ("lips", "1F48B", "ริมฝีปาก", "rim fii pak", "lips", "lips", "body"),
        ("thumbs_up", "1F44D", "เจ๋ง", "jeng", "thumbs up", "thumbs up", "body"),
        ("ok_hand", "1F44C", "โอเค", "oo khee", "OK hand", "OK", "body"),
        ("clap", "1F44F", "ปรบมือ", "prop mue", "clap", "applaudir", "body"),
        ("muscle", "1F4AA", "แขน", "khaen", "muscle", "muscle", "body"),
        ("skull", "1F480", "กะโหลก", "kaloke", "skull", "skull", "body"),
        ("bone", "1F9B4", "กระดูก", "kraduk", "bone", "os", "body"),
        ("lungs", "1FAC1", "ปอด", "pot", "lungs", "lungs", "body"),
        ("notes", "1F3B6", "โน้ตดนตรี", "not dontrii", "musical notes", "musical notes", "music"),
        ("headphone", "1F3A7", "หูฟัง", "huu fang", "headphones", "headphones", "music"),
        ("radio", "1F4FB", "วิทยุ", "witthayu", "radio", "radio", "music"),
        ("smile_soft", "1F60A", "อายยิ้ม", "aai yim", "blushing", "rougissant", "feelings"),
        ("thinking", "1F914", "คิด", "khit", "thinking", "thinking", "feelings"),
        ("star_struck", "1F929", "ตื่นเต้น", "tuen ten", "star-struck", "star-struck", "feelings"),
        ("hug", "1F917", "กอด", "kot", "hug", "étreinte", "feelings"),
        ("pleading", "1F97A", "ขอร้อง", "khor rong", "pleading", "pleading", "feelings"),
        ("tired", "1F62B", "เหนื่อย", "nueai", "tired", "fatigué", "feelings"),
        ("hot_face", "1F975", "ร้อน", "ron", "hot", "chaud", "feelings"),
        ("cold_face", "1F976", "หนาว", "naao", "cold", "froid", "feelings"),
        ("sneeze", "1F927", "จาม", "chaam", "sneeze", "sneeze", "feelings"),
        ("nerd", "1F913", "เนิร์ด", "noet", "nerd", "nerd", "feelings"),
        ("cowboy_f", "1F920", "คาวบอย", "khaowboi", "cowboy face", "cowboy visage", "feelings"),
        ("clown_f", "1F921", "ตัวตลก", "tua talok", "clown face", "clown visage", "feelings"),
        ("yum", "1F60B", "อร่อย", "aroi", "yum", "yum", "feelings"),
        ("baby", "1F476", "ทารก", "thaarok", "baby", "bébé", "family"),
        ("boy", "1F466", "เด็กผู้ชาย", "dek phu chaai", "boy", "garçon", "family"),
        ("girl", "1F467", "เด็กผู้หญิง", "dek phu ying", "girl", "fille", "family"),
        ("man", "1F468", "ผู้ชาย", "phu chaai", "man", "homme", "family"),
        ("woman", "1F469", "ผู้หญิง", "phu ying", "woman", "femme", "family"),
        ("old_man", "1F474", "คุณตา", "khun taa", "grandfather", "grandfather", "family"),
        ("old_woman", "1F475", "คุณยาย", "khun yaai", "grandmother", "grandmother", "family"),
        ("pregnant", "1F930", "ท้อง", "thong", "pregnant", "pregnant", "family"),
        ("princess", "1F478", "เจ้าหญิง", "jao ying", "princess", "princesse", "family"),
        ("prince", "1F934", "เจ้าชาย", "jao chaai", "prince", "prince", "family"),
        ("santa", "1F385", "ซานต้า", "saantaa", "Santa Claus", "Père Noël", "family"),
        ("angel", "1F47C", "นางฟ้า", "naang faa", "angel", "ange", "family"),
        ("ghost", "1F47B", "ผี", "phii", "ghost", "fantôme", "family"),
        ("alien", "1F47D", "เอเลี่ยน", "eelian", "alien", "extraterrestre", "family"),
        ("robot_face", "1F916", "หุ่นยนต์", "hun yon", "robot", "robot", "family"),
        ("w_sun", "2600", "แดด", "daet", "sun", "soleil", "weather"),
        ("w_cloud", "2601", "เมฆ", "meek", "cloud", "nuage", "weather"),
        ("w_partly", "26C5", "มีเมฆบ้าง", "mii meek bang", "partly cloudy", "partly cloudy", "weather"),
        ("w_rain", "1F327", "ฝนตก", "fon tok", "rain", "pluie", "weather"),
        ("w_thunder", "1F329", "ฟ้าผ่า", "faa phaa", "thunderstorm", "thunderstorm", "weather"),
        ("w_lightning", "26A1", "ฟ้าแลบ", "faa laep", "lightning", "éclair", "weather"),
        ("w_snow", "1F328", "หิมะตก", "hima tok", "snow", "neige", "weather"),
        ("w_tornado", "1F32A", "พายุ", "phayu", "tornado", "tornade", "weather"),
        ("w_fog", "1F32B", "หมอก", "mok", "fog", "brouillard", "weather"),
        ("w_wind", "1F32C", "ลม", "lom", "wind", "vent", "weather"),
        ("w_umbrella", "2614", "ร่มฝน", "rom fon", "umbrella", "umbrella", "weather"),
        ("w_thermo", "1F321", "อุณหภูมิ", "unhaphum", "temperature", "temperature", "weather"),
        ("w_sun_face", "1F31E", "อาทิตย์", "aathit", "sun face", "soleil visage", "weather"),
        ("w_new_moon", "1F311", "จันทร์ดับ", "chan dap", "new moon", "neuf lune", "weather"),
        ("s_soccer", "26BD", "ฟุตบอล", "futbon", "soccer", "soccer", "sport"),
        ("s_basket", "1F3C0", "บาสเกตบอล", "basketbon", "basketball", "basketball", "sport"),
        ("s_baseball", "26BE", "เบสบอล", "besbon", "baseball", "baseball", "sport"),
        ("s_tennis", "1F3BE", "เทนนิส", "thenit", "tennis", "tennis", "sport"),
        ("s_volley", "1F3D0", "วอลเลย์บอล", "wollebon", "volleyball", "volleyball", "sport"),
        ("s_rugby", "1F3C9", "รักบี้", "rakbii", "rugby", "rugby", "sport"),
        ("s_pingpong", "1F3D3", "ปิงปอง", "pingpong", "ping pong", "ping pong", "sport"),
        ("s_badminton", "1F3F8", "แบดมินตัน", "baedminton", "badminton", "badminton", "sport"),
        ("s_hockey", "1F3D2", "ฮอกกี้", "hokkii", "hockey", "hockey", "sport"),
        ("s_bowling", "1F3B3", "โบว์ลิ่ง", "boling", "bowling", "bowling", "sport"),
        ("s_billiard", "1F3B1", "พูล", "puun", "billiards", "billard", "sport"),
        ("s_running", "1F3C3", "วิ่ง", "wing", "running", "courir", "sport"),
        ("s_swimming", "1F3CA", "ว่ายน้ำ", "waai nam", "swimming", "nager", "sport"),
        ("s_surfing", "1F3C4", "โต้คลื่น", "to khluen", "surfing", "surfing", "sport"),
        ("s_skiing", "26F7", "สกี", "sakii", "skiing", "skiing", "sport"),
        ("s_snowboard", "1F3C2", "สโนว์บอร์ด", "sanoobot", "snowboarding", "snowboarding", "sport"),
        ("s_biking", "1F6B4", "ขี่จักรยาน", "khii chakrayaan", "cycling", "cycling", "sport"),
        ("s_golf", "1F3CC", "กอล์ฟ", "kop", "golf", "golf", "sport"),
        ("s_boxing", "1F94A", "มวย", "muai", "boxing", "boxe", "sport"),
        ("s_martial", "1F94B", "คาราเต้", "khaaraatee", "martial arts", "martial arts", "sport"),
        ("s_fishing", "1F3A3", "ตกปลา", "tok plaa", "fishing", "pêcher", "sport"),
        ("sch_school", "1F3EB", "โรงเรียน", "rong rian", "school", "école", "school"),
        ("sch_books", "1F4DA", "หนังสือ", "nangseu", "books", "livres", "school"),
        ("sch_notebook", "1F4D3", "สมุด", "samut", "notebook", "notebook", "school"),
        ("sch_pen", "1F58A", "ปากกา", "paakkaa", "pen", "stylo", "school"),
        ("sch_brush", "1F58C", "พู่กัน", "phuu kan", "brush", "brosse", "school"),
        ("sch_paperclip", "1F4CE", "คลิปหนีบ", "khlip nip", "paperclip", "paperclip", "school"),
        ("sch_ruler", "1F4CF", "ไม้บรรทัด", "mai banthat", "ruler", "ruler", "school"),
        ("sch_triangle", "1F4D0", "ไม้ฉาก", "mai chaak", "triangle", "triangle", "school"),
        ("sch_abc", "1F524", "ตัวอักษร", "tua aksorn", "ABC", "ABC", "school"),
        ("sch_memo", "1F4DD", "บันทึก", "banthuek", "memo", "memo", "school"),
        ("sch_calendar", "1F4C5", "ปฏิทิน", "patithin", "calendar", "calendar", "school"),
        ("sch_globe", "1F30F", "ลูกโลก", "luuk lok", "globe", "globe", "school"),
        ("sch_abacus", "1F9EE", "ลูกคิด", "luuk khit", "abacus", "boulier", "school"),
        ("sch_magnify", "1F50D", "แว่นขยาย", "waen khayaai", "magnifying glass", "magnifying glass", "school"),
        ("j_police", "1F46E", "ตำรวจ", "tamruat", "police officer", "policier officer", "characters"),
        ("j_guard", "1F482", "ทหารยาม", "thahan yaam", "guard", "guard", "characters"),
        ("j_detective", "1F575", "นักสืบ", "nak suep", "detective", "detective", "characters"),
        ("j_ninja", "1F977", "นินจา", "nincha", "ninja", "ninja", "characters"),
        ("j_superhero", "1F9B8", "ซูเปอร์ฮีโร่", "supoehiiroo", "superhero", "super-héros", "characters"),
        ("j_wizard", "1F9D9", "พ่อมด", "phormot", "wizard", "magicien", "characters"),
        ("j_vampire", "1F9DB", "แวมไพร์", "waemphai", "vampire", "vampire", "characters"),
        ("j_mermaid", "1F9DC", "นางเงือก", "naang nguak", "mermaid", "mermaid", "characters"),
        ("j_fairy", "1F9DA", "ภูต", "phuut", "fairy", "fairy", "characters"),
        ("j_elf", "1F9DD", "เอลฟ์", "elf", "elf", "elf", "characters"),
        ("j_genie", "1F9DE", "จินนี่", "chinnii", "genie", "genie", "characters"),
        ("j_zombie", "1F9DF", "ซอมบี้", "sombii", "zombie", "zombie", "characters"),
        ("t_video", "1F4F9", "กล้องวิดีโอ", "klong widio", "video camera", "video camera", "tech"),
        ("t_movie", "1F3A5", "ภาพยนตร์", "phaapayon", "movie", "movie", "tech"),
        ("t_game", "1F3AE", "เกม", "kem", "video game", "video game", "tech"),
        ("t_plug", "1F50C", "ปลั๊ก", "plak", "plug", "plug", "tech"),
        ("t_keyboard", "2328", "แป้นพิมพ์", "paen phim", "keyboard", "keyboard", "tech"),
        ("t_mouse", "1F5B1", "เมาส์", "mao", "mouse", "souris", "tech"),
        ("t_printer", "1F5A8", "เครื่องพิมพ์", "khrueang phim", "printer", "printer", "tech"),
        ("t_cd", "1F4BF", "แผ่นซีดี", "phaen siidii", "CD", "CD", "tech"),
        ("t_satellite", "1F6F0", "ดาวเทียม", "daao thiam", "satellite", "satellite", "tech"),
        ("t_magnet", "1F9F2", "แม่เหล็ก", "mae lek", "magnet", "magnet", "tech"),
        ("t_gear", "2699", "เฟือง", "fueang", "gear", "gear", "tech"),
        ("rice_ball", "1F359", "ข้าวปั้น", "khao pan", "rice ball", "riz ballon", "food"),
        ("dumpling", "1F95F", "เกี๊ยว", "kiao", "dumpling", "ravioli", "food"),
        ("oden", "1F362", "โอเด้ง", "ooden", "oden", "oden", "food"),
        ("dango", "1F361", "ดังโงะ", "dango", "dango", "dango", "food"),
        ("fried_shrimp", "1F364", "กุ้งทอด", "kung thot", "fried shrimp", "crevettes frites", "food"),
        ("fondue", "1FAD5", "ฟองดู", "fongduu", "fondue", "fondue", "food"),
        ("salt", "1F9C2", "เกลือ", "kluea", "salt", "sel", "food"),
        ("cooking", "1F373", "ทำอาหาร", "tham aahaan", "cooking", "cooking", "food"),
        ("mount_fuji", "1F5FB", "ภูเขาฟูจิ", "phu khao fuji", "Mount Fuji", "Mont Fuji", "nature"),
        ("sparkles", "2728", "ประกาย", "prakaai", "sparkles", "sparkles", "nature"),
        ("collision", "1F4A5", "ปัง", "pang", "collision", "collision", "nature"),
        ("zzz", "1F4A4", "หลับ", "lap", "sleeping", "sleeping", "feelings"),
        ("comet", "2604", "ดาวหาง", "daao haang", "comet", "comet", "space"),
        ("planet", "1FA90", "ดาวเคราะห์", "daao khror", "planet", "planet", "space"),
        ("saturn", "1FA90", "ดาวเสาร์", "daao sao", "Saturn", "Saturne", "space"),
        ("ringed_planet", "1FA90", "ดาวมีวงแหวน", "daao mii wong waen", "ringed planet", "ringed planet", "space"),
        ("galaxy", "1F30C", "ทางช้างเผือก", "thaang chang phueak", "galaxy", "galaxy", "space"),
        ("telescope_2", "1F52D", "กล้องส่องดาว", "klong song daao", "telescope", "telescope", "space"),
        ("rocket_2", "1F680", "จรวดอวกาศ", "charuat owakaat", "space rocket", "space rocket", "space"),
        ("satellite_2", "1F6F0", "ดาวเทียมอวกาศ", "daao thiam owakaat", "satellite", "satellite", "space"),
        ("astronaut", "1F468-200D-1F680", "นักบินอวกาศ", "nakbin owakaat", "astronaut", "astronaute", "space"),
        ("ufo_2", "1F6F8", "จานบิน", "chaan bin", "flying saucer", "flying saucer", "space"),
        ("alien_2", "1F47D", "มนุษย์ต่างดาว", "manut taang daao", "alien", "extraterrestre", "space"),
        ("t_rex", "1F996", "ทีเร็กซ์", "thii rek", "T-Rex", "T-Rex", "dinos"),
        ("brachiosaurus", "1F995", "แบรคิโอซอรัส", "braakhio-sao-rat", "brachiosaurus", "brachiosaure", "dinos"),
        ("triceratops", "1F996", "ไตรเซอราทอปส์", "traisoerathop", "triceratops", "triceratops", "dinos"),
        ("stegosaurus", "1F996", "สเตโกซอรัส", "sateekoosao-rat", "stegosaurus", "stegosaurus", "dinos"),
        ("pterodactyl", "1F996", "เทอโรแดกทิล", "thoeroodaek-thil", "pterodactyl", "pterodactyl", "dinos"),
        ("dino_egg", "1F95A", "ไข่ไดโนเสาร์", "khai dainosao", "dino egg", "dino oeuf", "dinos"),
        ("fossil", "1F9B4", "ฟอสซิล", "fotsin", "fossil", "fossil", "dinos"),
        ("city", "1F3D9", "เมือง", "muang", "city", "city", "places"),
        ("park", "1F3DE", "สวนสาธารณะ", "suan saatharana", "park", "parc", "places"),
        ("hospital", "1F3E5", "โรงพยาบาล", "rong phayaabaan", "hospital", "hôpital", "places"),
        ("bank", "1F3E6", "ธนาคาร", "thanaakhaan", "bank", "banque", "places"),
        ("hotel", "1F3E8", "โรงแรม", "rong raem", "hotel", "hotel", "places"),
        ("store", "1F3EC", "ห้างสรรพสินค้า", "haang sapphasinkhaa", "store", "store", "places"),
        ("castle", "1F3F0", "ปราสาท", "praasaat", "castle", "castle", "places"),
        ("temple", "1F30D", "วัด", "wat", "temple", "temple", "places"),
        ("factory", "1F3ED", "โรงงาน", "rong ngaan", "factory", "factory", "places"),
        ("farm", "1F3DC", "ฟาร์ม", "faam", "farm", "farm", "places"),
        ("mount_fuji_2", "1F5FB", "ภูเขาไฟฟูจิ", "phu khao fai fuji", "Mount Fuji", "Mont Fuji", "places"),
        ("bridge", "1F309", "สะพาน", "saphaan", "bridge", "pont", "places"),
        ("camping", "1F3D5", "แคมป์ปิ้ง", "khaemping", "camping", "camping", "places"),
        ("tent", "26FA", "เต็นท์", "ten", "tent", "tent", "places"),
        ("circle", "26AA", "วงกลม", "wong klom", "circle", "circle", "shapes"),
        ("square", "2B1B", "สี่เหลี่ยม", "sii liam", "square", "square", "shapes"),
        ("triangle_s", "1F53A", "สามเหลี่ยม", "saam liam", "triangle", "triangle", "shapes"),
        ("heart_s", "2764", "รูปหัวใจ", "ruup huachai", "heart shape", "coeur shape", "shapes"),
        ("star_s", "2B50", "รูปดาว", "ruup daao", "star shape", "étoile shape", "shapes"),
        ("diamond_s", "1F536", "รูปข้าวหลามตัด", "ruup khaow laam tat", "diamond shape", "diamond shape", "shapes"),
        ("oval", "2B55", "วงรี", "wong rii", "oval", "oval", "shapes"),
        ("cloud_s", "2601", "รูปเมฆ", "ruup meek", "cloud shape", "nuage shape", "shapes"),
        ("moon_s", "1F319", "รูปพระจันทร์", "ruup phra chan", "moon shape", "lune shape", "shapes"),
        ("rain_s", "1F327", "รูปฝน", "ruup fon", "rain shape", "pluie shape", "shapes"),
        ("fire_s", "1F525", "รูปไฟ", "ruup fai", "fire shape", "feu shape", "shapes"),
        ("cross", "274C", "กากบาท", "kaakabaat", "cross", "cross", "shapes"),
        ("arrow_up", "2B06", "ลูกศรขึ้น", "luk sorn kheun", "arrow up", "flèche haut", "shapes"),
        ("arrow_down", "2B07", "ลูกศรลง", "luk sorn long", "arrow down", "flèche bas", "shapes"),
        ("arrow_left", "2B05", "ลูกศรซ้าย", "luk sorn saai", "arrow left", "flèche gauche", "shapes"),
        ("arrow_right", "27A1", "ลูกศรขวา", "luk sorn khwaa", "arrow right", "flèche droite", "shapes"),
        ("hammer", "1F528", "ค้อน", "khon", "hammer", "hammer", "home"),
        ("axe", "1FA93", "ขวาน", "khwaan", "axe", "hache", "tools"),
        ("pick", "26CF", "อีเต้อ", "ii toe", "pickaxe", "pickaxe", "tools"),
        ("wrench", "1F527", "ประแจ", "prachae", "wrench", "wrench", "tools"),
        ("screwdriver", "1FA9B", "ไขควง", "khai khuang", "screwdriver", "screwdriver", "tools"),
        ("nut_bolt", "1F529", "น็อต", "not", "nut and bolt", "nut et bolt", "tools"),
        ("saw", "1FA9A", "เลื่อย", "lueai", "saw", "saw", "tools"),
        ("ladder", "1FA9C", "บันไดลิง", "bandai ling", "ladder", "ladder", "tools"),
        ("toolbox", "1F9F0", "กล่องเครื่องมือ", "klong khrueang mue", "toolbox", "toolbox", "tools"),
        ("magnifying", "1F50D", "แว่นขยาย", "waen khayaai", "magnifying glass", "magnifying glass", "tools"),
        ("butterfly_2", "1F98B", "ผีเสื้อสวย", "phii suea suay", "butterfly", "papillon", "insects"),
        ("bug", "1F41B", "หนอน", "non", "caterpillar", "caterpillar", "insects"),
        ("ant_2", "1F41C", "มดดำ", "mot dam", "black ant", "fourmi noire", "insects"),
        ("bee_2", "1F41D", "ผึ้งน้อย", "pheung noi", "honeybee", "honeybee", "insects"),
        ("ladybug_2", "1F41E", "เต่าทองแดง", "tao thong daeng", "ladybug", "coccinelle", "insects"),
        ("cricket", "1F997", "จิ้งหรีด", "ching rit", "cricket", "cricket", "insects"),
        ("spider_2", "1F577", "แมงมุมดำ", "maengmum dam", "spider", "araignée", "insects"),
        ("spider_web", "1F578", "ใยแมงมุม", "yai maengmum", "spider web", "araignée web", "insects"),
        ("scorpion_2", "1F982", "แมงป่องพิษ", "maengpong phit", "scorpion", "scorpion", "insects"),
        ("mosquito_2", "1F99F", "ยุงลาย", "yung laai", "mosquito", "mosquito", "insects"),
        ("fly", "1FAB0", "แมลงวัน", "ma laeng wan", "fly", "voler", "insects"),
        ("worm_2", "1FAB1", "หนอนดิน", "non din", "earthworm", "earthworm", "insects"),
        ("beetle_2", "1FAB2", "ด้วงกว่าง", "duang kwang", "beetle", "scarabée", "insects"),
        ("cockroach", "1FAB3", "แมลงสาบ", "ma laeng saab", "cockroach", "cockroach", "insects"),
        ("firecracker", "1F9E8", "ประทัด", "prathat", "firecracker", "firecracker", "events"),
        ("fireworks", "1F386", "พลุ", "phlu", "fireworks", "feu d'artifice", "events"),
        ("sparkler", "1F387", "ดอกไม้ไฟ", "dok mai fai", "sparkler", "sparkler", "events"),
        ("balloon_2", "1F388", "ลูกโป่งสวรรค์", "luk pong sawan", "balloon", "ballon", "events"),
        ("party_popper", "1F389", "พลุกระดาษ", "phlu kradat", "party popper", "fête popper", "events"),
        ("confetti", "1F38A", "สายรุ้ง", "saai rung", "confetti ball", "confetti ballon", "events"),
        ("tanabata", "1F38B", "ต้นทานาบาตะ", "ton thaanabaata", "wish tree", "wish arbre", "events"),
        ("pine_deco", "1F38D", "ต้นสนประดับ", "ton son pradap", "pine deco", "pine deco", "events"),
        ("dolls", "1F38E", "ตุ๊กตาญี่ปุ่น", "tukkata yipun", "dolls", "dolls", "events"),
        ("carp_streamer", "1F38F", "ธงปลาคาร์พ", "thong plaa khaap", "carp streamer", "carp streamer", "events"),
        ("wind_chime", "1F390", "กระดิ่งลม", "kradeng lom", "wind chime", "vent chime", "events"),
        ("moon_viewing", "1F391", "ชมจันทร์", "chom chan", "moon viewing", "lune viewing", "events"),
        ("red_envelope", "1F9E7", "อั่งเปา", "ang pao", "red envelope", "enveloppe rouge", "events"),
        ("gift", "1F381", "ของขวัญ", "khong khwan", "gift", "cadeau", "events"),
        ("ribbon", "1F380", "โบว์", "boo", "ribbon", "ribbon", "events"),
        ("christmas_tree", "1F384", "ต้นคริสต์มาส", "ton khritmaat", "Christmas tree", "Sapin de Noël", "events"),
        ("jack_o_lantern", "1F383", "ฟักทองฮาโลวีน", "fak thong haaloowiin", "Halloween pumpkin", "Citrouille d'Halloween", "events"),
        ("bamboo", "1F38D", "ไม้ไผ่", "mai phai", "bamboo", "bambou", "nature"),
        ("palm_tree_2", "1F334", "ต้นมะพร้าว", "ton maphrao", "palm tree", "palm arbre", "nature"),
        ("cactus_2", "1F335", "กระบองเพชร", "krabong phet", "cactus", "cactus", "nature"),
        ("herb", "1F33F", "สมุนไพร", "samun phrai", "herb", "herb", "nature"),
        ("shamrock", "2618", "ใบไม้สามแฉก", "bai mai saam chaek", "shamrock", "shamrock", "nature"),
        ("four_leaf", "1F340", "ใบโคลเวอร์", "bai khloowoe", "four leaf clover", "quatre leaf clover", "nature"),
        ("maple_2", "1F341", "ใบเมเปิ้ลสีแดง", "bai meepoen sii daeng", "maple leaf", "maple leaf", "nature"),
        ("fallen_leaf_2", "1F342", "ใบไม้แห้ง", "bai mai haeng", "fallen leaf", "fallen leaf", "nature"),
        ("leaf_flutter", "1F343", "ใบไม้ปลิว", "bai mai pliu", "leaves in wind", "leaves in vent", "nature"),
        ("empty_nest", "1FAB9", "รังนกว่าง", "rang nok waang", "empty nest", "vider nest", "nature"),
        ("nest_with_eggs", "1FABA", "รังนกมีไข่", "rang nok mii khai", "nest with eggs", "nest with eggs", "nature"),
        ("lotus", "1FABB", "ดอกบัว", "dok bua", "lotus", "lotus", "nature"),
        ("rock", "1FAA8", "ก้อนหิน", "kon hin", "rock", "roche", "nature"),
        ("wood", "1FAB5", "ไม้", "mai", "wood", "wood", "nature"),
        ("logs", "1FAB5", "ท่อนไม้", "thon mai", "logs", "logs", "nature"),
        ("seed", "1F331", "เมล็ดพันธุ์", "malet phan", "seed", "seed", "nature"),
        ("shell_2", "1F41A", "หอย", "hoi", "shell", "shell", "nature"),
        ("microscope", "1F52C", "กล้องจุลทรรศน์", "klong chun lathat", "microscope", "microscope", "tools"),
        ("telescope", "1F52D", "กล้องโทรทรรศน์", "klong thoorathat", "telescope", "telescope", "tools"),
        ("compass", "1F9ED", "เข็มทิศ", "khem thit", "compass", "compass", "tools"),
        ("flashlight", "1F526", "ไฟฉาย", "fai chaai", "flashlight", "flashlight", "tools"),
        ("candle", "1F56F", "เทียน", "thian", "candle", "candle", "home"),
        ("lamp", "1FA94", "โคมไฟ", "khoom fai", "lamp", "lampe", "home"),
        ("table", "1FA91", "โต๊ะ", "to", "table", "table", "home"),
        ("bed_2", "1F6CF", "เตียงนอน", "tiang non", "single bed", "single lit", "home"),
        ("pillow", "1F6CC", "หมอน", "morn", "pillow", "pillow", "home"),
        ("blanket", "1F9F1", "ผ้าห่ม", "phaa hom", "blanket", "couverture", "home"),
        ("t_helicopter", "1F681", "เฮลิคอปเตอร์กู้ภัย", "heelikhoptoe", "rescue helicopter", "rescue helicopter", "transport"),
        ("t_skate", "1F6F9", "สเกตบอร์ด", "saketbot", "skateboard", "skateboard", "transport"),
        ("t_scooter", "1F6F4", "สกู๊ตเตอร์", "sakuttoe", "scooter", "scooter", "transport"),
        ("t_cable_car", "1F6A0", "กระเช้าลอยฟ้า", "krachao loy faa", "cable car", "cable voiture", "transport"),
        ("t_ferry", "26F4", "เรือข้ามฟาก", "ruea khaam faak", "ferry", "ferry", "transport"),
        ("t_canoe", "1F6F6", "เรือแคนู", "ruea khaenuu", "canoe", "canoe", "transport"),
        ("t_parachute", "1FA82", "ร่มชูชีพ", "rom chuu chiip", "parachute", "parachute", "transport"),
        ("t_flying_saucer", "1F6F8", "จานบินลึกลับ", "chaan bin", "UFO", "OVNI", "transport"),
        ("t_stretcher", "1F691", "เปลหาม", "plee haam", "stretcher", "stretcher", "transport"),
        ("t_wheelchair", "1F9BD", "เก้าอี้รถเข็น", "kao-ii rot khen", "wheelchair", "wheelchair", "transport"),
        ("m_accordion", "1FA77", "หีบเพลง", "hiip phleeng", "accordion", "accordéon", "music"),
        ("m_long_drum", "1F941", "กลองยาว", "klong yaao", "long drum", "long tambour", "music"),
        ("m_banjo", "1FA95", "แบนโจ", "baen-choo", "banjo", "banjo", "music"),
        ("m_flute", "1FA77", "ขลุ่ย", "khlui", "flute", "flûte", "music"),
        ("m_violin_2", "1F3BB", "สีซอ", "sii sor", "Thai violin", "Violon thaï", "music"),
        ("m_maracas", "1FA87", "มาราคัส", "maaraakhat", "maracas", "maracas", "music"),
        ("m_radio_2", "1F4FB", "เครื่องเล่นวิทยุ", "witthayu", "radio", "radio", "music"),
        ("e_backpack", "1F392", "กระเป๋านักเรียน", "krapao nakrian", "school bag", "école sac", "school"),
        ("e_pencil_case", "1F4DA", "กล่องดินสอ", "klong dinso", "pencil case", "crayon case", "school"),
        ("e_eraser", "1F4DA", "ยางลบ", "yaang lop", "eraser", "eraser", "school"),
        ("e_crayon", "1F58D", "สีเทียน", "sii thian", "crayon", "crayon", "school"),
        ("e_marker", "1F58B", "ปากกาเมจิก", "paakkaa mechik", "marker", "marker", "school"),
        ("e_paint_palette", "1F3A8", "จานสี", "chaan sii", "palette", "palette", "school"),
        ("e_blackboard", "1F3EB", "กระดานดำ", "kradan dam", "blackboard", "tableau noir", "school"),
        ("e_desk", "1FA91", "โต๊ะเรียน", "to rian", "school desk", "école desk", "school"),
        ("e_light_bulb", "1F4A1", "ปัญญา", "panyaa", "idea", "idea", "school"),
        ("j_doctor", "1F468-200D-2695-FE0F", "หมอ", "mor", "doctor", "médecin", "characters"),
        ("j_nurse", "1F469-200D-2695-FE0F", "พยาบาล", "phayaabaan", "nurse", "infirmière", "characters"),
        ("j_cook", "1F468-200D-1F373", "พ่อครัว", "phor khrua", "cook", "cuisinier", "characters"),
        ("j_artist", "1F468-200D-1F3A8", "ศิลปิน", "sinlapin", "artist", "artiste", "characters"),
        ("j_pilot", "1F468-200D-2708-FE0F", "นักบิน", "nakbin", "pilot", "pilote", "characters"),
        ("j_firefighter", "1F468-200D-1F692", "นักดับเพลิง", "nak dap phloeng", "firefighter", "pompier", "characters"),
        ("j_teacher", "1F468-200D-1F3EB", "คุณครู", "khun khruu", "teacher", "professeur", "characters"),
        ("j_scientist", "1F468-200D-1F52C", "นักวิทยาศาสตร์", "nak witthayaasaat", "scientist", "scientifique", "characters"),
        ("j_astronaut_2", "1F468-200D-1F680", "นักบินอวกาศ", "nakbin owakaat", "astronaut", "astronaute", "characters"),
        ("v_sock", "1F9E6", "ถุงเท้ายาว", "thung thao yaao", "long sock", "long chaussette", "clothes"),
        ("v_mitten", "1F9E4", "ถุงมือกันหนาว", "thung mue kan naao", "mitten", "mitten", "clothes"),
        ("v_belt", "1F456", "เข็มขัด", "khem khat", "belt", "ceinture", "clothes"),
        ("v_tie", "1F454", "เนคไท", "nekthai", "necktie", "necktie", "clothes"),
        ("v_scarf_2", "1F9E3", "ผ้าพันคอสีแดง", "phaa phan khor", "red scarf", "écharpe rouge", "clothes"),
        ("v_safety_vest", "1F9BA", "เสื้อกั๊กสะท้อนแสง", "suea kak", "safety vest", "safety vest", "clothes"),
        ("v_lab_coat", "1F97C", "เสื้อกาวน์", "suea kaao", "lab coat", "lab manteau", "clothes"),
        ("v_clog", "1FA74", "รองเท้าอุดรู", "rongthao", "clog", "clog", "clothes"),
        ("v_ballet", "1FA70", "รองเท้าบัลเลต์", "rongthao ballee", "ballet shoes", "chaussons de ballet", "clothes"),
        ("c_tongue", "1F445", "แลบลิ้น", "laep lin", "sticking tongue out", "sticking langue out", "body"),
        ("c_ear_2", "1F442", "ฟังเสียง", "fang siang", "listening", "listening", "body"),
        ("c_nose_2", "1F443", "ดมกลิ่น", "dom klin", "smelling", "smelling", "body"),
        ("c_eyes", "1F440", "มองดู", "mong duu", "looking", "looking", "body"),
        ("c_hair", "1F9B0", "เส้นผม", "sen phom", "hair", "cheveux", "body"),
        ("c_bone_2", "1F9B4", "กระดูกคน", "kraduk khon", "human bone", "human os", "body"),
        ("c_tooth_2", "1F9B7", "ฟันน้ำนม", "fan nam nom", "baby tooth", "dent de lait", "body"),
        ("c_heart_2", "1FAC0", "หัวใจเต้น", "huachai ten", "beating heart", "coeur qui bat", "body"),
        ("c_brain_2", "1F9E0", "สมองคน", "samong khon", "human brain", "human cerveau", "body"),
        ("c_stomach", "1FAC1", "ท้อง", "thong", "stomach", "stomach", "body"),
        ("c_feet", "1F9B6", "เท้าคู่", "thao khuu", "feet", "feet", "body"),
        ("c_hands", "1F450", "สองมือ", "song mue", "two hands", "deux hands", "body"),
        ("c_kneel", "1F9CE", "คุกเข่า", "khuk khao", "kneeling", "kneeling", "body"),
        ("c_standing", "1F9CD", "ยืน", "yuen", "standing", "standing", "body"),
        ("c_walking", "1F6B6", "เดิน", "doen", "walking", "walking", "body"),
        ("c_running_2", "1F3C3", "วิ่งเร็ว", "wing reo", "running fast", "courir rapide", "body"),
        ("rug", "1FA96", "พรม", "phrom", "rug", "tapis", "home"),
        ("curtain", "1FA97", "ผ้าม่าน", "phaa maan", "curtain", "rideau", "home"),
        ("mirror_2", "1FA9E", "กระจกเงา", "krachok ngao", "wall mirror", "mur mirror", "home"),
        ("picture_frame", "1F5BC", "กรอบรูป", "krop ruup", "frame", "frame", "home"),
        ("vase", "1F3FA", "แจกัน", "chaekan", "vase", "vase", "home"),
        ("wastebasket", "1F5D1", "ถังขยะ", "thang khaya", "wastebasket", "wastebasket", "home"),
        ("mop", "1F9FA", "ไม้ม็อบ", "mai mop", "mop", "mop", "home"),
        ("bucket_2", "1FAA3", "ถังน้ำ", "thang nam", "water bucket", "eau seau", "home"),
        ("shower_2", "1F6BF", "อาบน้ำ", "aap nam", "showering", "showering", "hygiene"),
        ("bathtub_2", "1F6C1", "แช่น้ำ", "chae nam", "taking a bath", "taking a bain", "hygiene"),
        ("b_swan", "1F9A2", "หงส์ขาว", "hong khaow", "white swan", "blanc cygne", "animals"),
        ("b_flamingo", "1F9A9", "นกฟลามิงโก้", "flamingkho", "flamingo", "flamingo", "animals"),
        ("b_peacock", "1F99A", "นกยูงรำแพน", "nok yung", "peacock", "peacock", "animals"),
        ("b_parrot", "1F99C", "นกแก้วมาคอว์", "nok kaeo", "parrot", "perroquet", "animals"),
        ("b_owl", "1F989", "นกฮูกตาโต", "nok huuk", "owl", "hibou", "animals"),
        ("b_penguin", "1F427", "เพนกวินน้อย", "pengwin", "penguin", "manchot", "animals"),
        ("b_eagle", "1F985", "พญาอินทรี", "phayaa insii", "eagle", "aigle", "animals"),
        ("b_duck", "1F986", "เป็ดก้าบก้าบ", "ped", "duck", "canard", "animals"),
        ("b_turkey", "1F983", "ไก่งวงตัวใหญ่", "kai nguang", "turkey", "turkey", "animals"),
        ("b_dove", "1F54A", "นกแห่งสันติภาพ", "nok phiraap", "dove", "dove", "animals"),
        ("b_rooster", "1F413", "ไก่โต้ง", "kai tong", "rooster", "rooster", "animals"),
        ("f_hibiscus", "1F33A", "ดอกชบาแดง", "chabaa", "hibiscus", "hibiscus", "nature"),
        ("f_cherry", "1F338", "ซากุระบาน", "saakuraa", "cherry blossom", "fleur de cerisier", "nature"),
        ("f_sunflower", "1F33B", "ทานตะวันยิ้ม", "thaantawan", "sunflower", "tournesol", "nature"),
        ("f_rose", "1F339", "กุหลาบแดง", "kulaap daeng", "red rose", "rose rouge", "nature"),
        ("f_tulip", "1F337", "ทิวลิปชมพู", "thiwlip", "pink tulip", "rose tulip", "nature"),
        ("f_blossom", "1F33C", "ดอกไม้ขาว", "dok mai khaow", "white flower", "fleur blanche", "nature"),
        ("a_reading", "1F4D6", "อ่านหนังสือ", "aan nangseu", "reading", "reading", "school"),
        ("a_writing", "270F", "เขียนหนังสือ", "khian nangseu", "writing", "writing", "school"),
        ("a_painting", "1F3A8", "ระบายสี", "rabaai sii", "painting", "painting", "school"),
        ("a_singing", "1F3A4", "ร้องเพลง", "rong phleeng", "singing", "chanter", "music"),
        ("a_dancing", "1F483", "เต้นรำ", "ten ram", "dancing", "danser", "music"),
        ("a_sleeping", "1F6CF", "นอนหลับ", "non lap", "sleeping", "sleeping", "home"),
        ("a_eating", "1F35A", "กินข้าว", "kin khao", "eating", "eating", "food"),
        ("a_drinking", "1F964", "ดื่มน้ำ", "duem nam", "drinking", "drinking", "drinks"),
        ("a_playing", "1F9F8", "เล่นตุ๊กตา", "len tukkata", "playing", "jouer", "toys"),
        ("a_climbing", "1F9D7", "ปีนเขา", "piin khao", "climbing", "climbing", "sport"),
        ("a_biking", "1F6B4", "ปั่นจักรยาน", "pan chakrayaan", "cycling", "cycling", "sport"),
        ("p_baby_2", "1F476", "เด็กทารก", "dek thaarok", "little baby", "little bébé", "family"),
        ("p_boy_2", "1F466", "เด็กชาย", "dek chaai", "young boy", "young garçon", "family"),
        ("p_girl_2", "1F467", "เด็กหญิง", "dek ying", "young girl", "young fille", "family"),
        ("p_grandpa", "1F474", "คุณปู่", "khun puu", "grandpa", "grandpa", "family"),
        ("p_grandma", "1F475", "คุณย่า", "khun yaa", "grandma", "grandma", "family"),
        ("p_king", "1F451", "พระราชา", "phra raachaa", "king", "roi", "characters"),
        ("p_queen", "1F478", "พระราชินี", "phra raachinii", "queen", "reine", "characters"),
        ("p_detective", "1F575", "นักสืบจิ๋ว", "nak suep", "detective", "detective", "characters"),
        ("p_spy", "1F575", "สายลับ", "saai lap", "spy", "spy", "characters"),
        ("p_superman", "1F9B8", "ยอดมนุษย์", "yot manut", "superhero", "super-héros", "characters"),
        ("p_ninja_2", "1F977", "นินจาชุดดำ", "nincha", "black ninja", "ninja noir", "characters"),
        ("p_vampire_2", "1F9DB", "ผีดูดเลือด", "phii duut lueat", "vampire", "vampire", "characters"),
        ("p_zombie_2", "1F9DF", "ผีดิบ", "phii dip", "zombie", "zombie", "characters"),
        ("p_genie_2", "1F9DE", "ยักษ์ในตะเกียง", "yak", "genie", "genie", "characters"),
        ("p_mermaid_2", "1F9DC", "เงือกน้อย", "nguak noi", "mermaid", "mermaid", "characters"),
        ("p_elf_2", "1F9DD", "เอลฟ์น้อย", "elf noi", "little elf", "little elf", "characters"),
        ("p_fairy_2", "1F9DA", "นางฟ้าตัวน้อย", "naang faa", "little fairy", "little fairy", "characters"),
        ("p_mage", "1F9D9", "จอมเวทย์", "chom wet", "mage", "magicien", "characters"),
        ("toilet_2", "1F6BD", "ขับถ่าย", "khap thaai", "using toilet", "using toilet", "hygiene"),
        ("sink", "1F6B0", "อ่างล้างมือ", "aang laang mue", "sink", "sink", "hygiene"),
        ("lotion", "1F9F4", "โลชั่น", "loochen", "lotion", "lotion", "hygiene"),
        ("shampoo", "1F9F4", "แชมพู", "chaem-phuu", "shampoo", "shampoing", "hygiene"),
        ("razor", "1FA92", "มีดโกน", "miit koon", "razor", "rasoir", "hygiene"),
        ("towel", "1F9F5", "ผ้าเช็ดตัว", "phaa chet tua", "towel", "serviette", "hygiene"),
        ("hair_brush", "1FA95", "หวี", "wii", "comb", "peigne", "hygiene"),
        ("mirror_f", "1FA9E", "ส่องกระจก", "song krachok", "looking in mirror", "looking in mirror", "hygiene"),
        ("soap_2", "1F9FC", "ล้างมือ", "laang mue", "washing hands", "washing hands", "hygiene"),
        ("toothpaste", "1FAA5", "ยาสีฟัน", "yaa sii fan", "toothpaste", "dentifrice", "hygiene"),
        ("t_laptop", "1F4BB", "โน้ตบุ๊ก", "not-buk", "laptop", "laptop", "tech"),
        ("t_smartphone", "1F4F1", "สมาร์ทโฟน", "samaat-foon", "smartphone", "smartphone", "tech"),
        ("t_desktop", "1F5A5", "คอมพิวเตอร์ตั้งโต๊ะ", "khom-phiu-toe", "desktop computer", "desktop ordinateur", "tech"),
        ("t_trackball", "1F5B2", "แทร็กบอล", "thraek-bon", "trackball", "trackball", "tech"),
        ("t_floppy", "1F4BD", "แผ่นดิสก์", "phaen-dik", "floppy disk", "floppy disk", "tech"),
        ("t_hard_disk", "1F4BE", "ฮาร์ดดิสก์", "haat-dik", "hard disk", "dur disk", "tech"),
        ("t_joystick_3", "1F579", "คันโยกเกม", "khan-yok", "joystick", "joystick", "tech"),
        ("t_webcam", "1F4F7", "เว็บแคม", "web-khaem", "webcam", "webcam", "tech"),
        ("t_server", "2699", "เซิร์ฟเวอร์", "soe-woe", "server", "server", "tech"),
        ("t_cable", "1F50C", "สายไฟ", "saai-fai", "cable", "cable", "tech"),
        ("o_bag", "1F45C", "กระเป๋าถือ", "krapao thue", "handbag", "sac à main", "clothes"),
        ("o_briefcase", "1F4BC", "กระเป๋าเอกสาร", "krapao eksaan", "briefcase", "mallette", "home"),
        ("o_parcel", "1F4E6", "พัสดุ", "phatsadu", "package", "package", "home"),
        ("o_mailbox", "1F4EB", "ตู้จดหมาย", "tuu chotmaai", "mailbox", "mailbox", "home"),
        ("o_telescope_3", "1F52D", "กล้องดูดาว", "klong duu daao", "telescope", "telescope", "space"),
        ("o_dna", "1F9EC", "ดีเอ็นเอ", "dii-en-ee", "DNA", "ADN", "tech"),
        ("o_test_tube", "1F9EA", "หลอดทดลอง", "lot thot long", "test tube", "test tube", "tech"),
        ("o_petri_dish", "1F9EB", "จานเพาะเชื้อ", "chaan phor chuea", "Petri dish", "Boîte de Pétri", "tech"),
        ("o_abacus_2", "1F9EE", "ลูกคิดไทย", "luuk khit", "abacus", "boulier", "school"),
        ("o_toolbox_2", "1F9F0", "กล่องเหล็ก", "klong lek", "toolbox", "toolbox", "tools"),
        ("o_fire_ext", "1F9EF", "ถังดับเพลิง", "thang dap phloeng", "fire extinguisher", "feu extinguisher", "home"),
        ("o_magnet_2", "1F9F2", "แม่เหล็กแรงสูง", "mae lek", "magnet", "magnet", "tech"),
        ("o_test_tube_2", "1F9EA", "หลอดแก้ว", "lot kaeo", "glass tube", "glass tube", "tech"),
        ("floss", "1F9F7", "ไหมขัดฟัน", "mai khat fan", "dental floss", "soie dentaire", "hygiene"),
        ("toilet_paper_2", "1F9FB", "ทิชชู่", "thit-chuu", "tissue", "tissue", "hygiene"),
        ("band_aid", "1FA79", "พลาสเตอร์", "phlaas-toe", "bandage", "pansement", "hygiene"),
        ("stethoscope", "1FA7A", "หูฟังหมอ", "huu fang mor", "stethoscope", "stethoscope", "hygiene"),
        ("thermometer", "1F321", "ปรอทวัดไข้", "parot wat khai", "thermometer", "thermometer", "hygiene"),
        ("syringe", "1F489", "เข็มฉีดยา", "khem chiit yaa", "syringe", "syringe", "hygiene"),
        ("pill", "1F48A", "ยาเม็ด", "yaa met", "pill", "pill", "hygiene"),
        ("crutch", "1FA7C", "ไม้เท้า", "mai thao", "crutch", "crutch", "hygiene"),
        ("wheelchair", "1F9BD", "รถเข็น", "rot khen", "wheelchair", "wheelchair", "hygiene"),
        ("run_v", "1F3C3", "วิ่ง", "wing", "run", "courir", "verbs"),
        ("jump_v", "1F9D3", "กระโดด", "kradot", "jump", "sauter", "verbs"),
        ("eat_v", "1F374", "กิน", "gin", "eat", "manger", "verbs"),
        ("sleep_v", "1F6CC", "นอน", "non", "sleep", "sommeil", "verbs"),
        ("walk_v", "1F6B6", "เดิน", "doen", "walk", "marcher", "verbs"),
        ("swim_v", "1F3CA", "ว่ายน้ำ", "waai nam", "swim", "nager", "verbs"),
        ("dance_v", "1F483", "เต้น", "ten", "dance", "danser", "verbs"),
        ("sing_v", "1F3A4", "ร้อง", "rong", "sing", "chanter", "verbs"),
        ("play_v", "1F6B2", "เล่น", "len", "play", "jouer", "verbs"),
        ("sit_v", "1F9F9", "นั่ง", "nang", "sit", "s'asseoir", "verbs"),
        ("stand_v", "1F647", "ยืน", "yuen", "stand", "se lever", "verbs"),
        ("read_v", "1F4D6", "อ่าน", "aan", "read", "lire", "verbs"),
        ("write_v", "1F58A", "เขียน", "khian", "write", "écrire", "verbs"),
        ("draw_v", "1F58C", "วาด", "wad", "draw", "dessiner", "verbs"),
        ("cook_v", "1F373", "ปรุงอาหาร", "pruang ahan", "cook", "cuisinier", "verbs"),
        ("drink_v", "1F60B", "ดื่ม", "duem", "drink", "boire", "verbs"),
        ("see_v", "1F440", "มอง", "mong", "see", "voir", "verbs"),
        ("hear_v", "1F442", "ได้ยิน", "dai yin", "hear", "entendre", "verbs"),
        ("touch_v", "1F91A", "แตะ", "tae", "touch", "toucher", "verbs"),
        ("laugh_v", "1F602", "หัวเราะ", "hua roe", "laugh", "rire", "verbs"),
        ("cry_v", "1F622", "ร้องไห้", "rong hai", "cry", "pleurer", "verbs"),
        ("smile_v", "1F603", "ยิ้ม", "yim", "smile", "sourire", "verbs"),
        ("wake_v", "1F60E", "ตื่น", "tuen", "wake up", "wake up", "verbs"),
        ("stop_v", "1F6D1", "หยุด", "yut", "stop", "arrêter", "verbs"),
        ("go_v", "1F6B4", "ไป", "pai", "go", "go", "verbs"),
        ("come_v", "1F44B", "มา", "maa", "come", "come", "verbs"),
        ("give_v", "1F91B", "ให้", "hai", "give", "donner", "verbs"),
        ("take_v", "1F456", "เอา", "ao", "take", "prendre", "verbs"),
        ("hold_v", "1F64F", "จับ", "chap", "hold", "tenir", "verbs"),
        ("throw_v", "1F4A8", "ปาะ", "pa", "throw", "lancer", "verbs"),
        ("big_a", "1F33B", "ใหญ่", "yai", "big", "grand", "adjectives"),
        ("small_a", "1F9AE", "เล็ก", "lek", "small", "petit", "adjectives"),
        ("tall_a", "1F974", "สูง", "sung", "tall", "grand", "adjectives"),
        ("short_a", "1F64F", "เตี้ย", "tia", "short", "court", "adjectives"),
        ("hot_a", "1F525", "ร้อน", "ron", "hot", "chaud", "adjectives"),
        ("cold_a", "1F976", "เย็น", "yen", "cold", "froid", "adjectives"),
        ("warm_a", "1F9A5", "อุ่น", "un", "warm", "tiède", "adjectives"),
        ("wet_a", "1F4A6", "เปียก", "piak", "wet", "mouillé", "adjectives"),
        ("dry_a", "1F6BD", "แห้ง", "haeng", "dry", "sec", "adjectives"),
        ("fast_a", "1F3C7", "เร็ว", "reo", "fast", "rapide", "adjectives"),
        ("slow_a", "1F40C", "ช้า", "chaa", "slow", "lent", "adjectives"),
        ("happy_a", "1F60A", "สุข", "suk", "happy", "heureux", "adjectives"),
        ("sad_a", "1F622", "เศร้า", "sao", "sad", "triste", "adjectives"),
        ("angry_a", "1F621", "โกรธ", "krot", "angry", "en colère", "adjectives"),
        ("tired_a", "1F60F", "เหนื่อย", "nueay", "tired", "fatigué", "adjectives"),
        ("strong_a", "1F929", "แข็งแรง", "khaeng raeng", "strong", "fort", "adjectives"),
        ("weak_a", "1F92E", "อ่อนแอ", "on ae", "weak", "faible", "adjectives"),
        ("clean_a", "1F9EA", "สะอาด", "sa at", "clean", "propre", "adjectives"),
        ("dirty_a", "1F4A9", "สกปรก", "sakprok", "dirty", "sale", "adjectives"),
        ("new_a", "1F195", "ใหม่", "mai", "new", "nouveau", "adjectives"),
        ("old_a", "1F9B2", "เก่า", "kao", "old", "ancien", "adjectives"),
        ("young_a", "1F466", "เด็ก", "dek", "young", "jeune", "adjectives"),
        ("beautiful_a", "1F590", "สวย", "suay", "beautiful", "beau", "adjectives"),
        ("ugly_a", "1F62E", "น่าเกลียด", "naa gliat", "ugly", "laid", "adjectives"),
        ("bright_a", "1F310", "สว่าง", "sawang", "bright", "lumineux", "adjectives"),
        ("dark_a", "1F303", "มืด", "muet", "dark", "sombre", "adjectives"),
        ("loud_a", "1F50A", "ดัง", "dang", "loud", "loud", "adjectives"),
        ("quiet_a", "1F92B", "เงียบ", "yip", "quiet", "quiet", "adjectives"),
        ("safe_a", "1F6E1", "ปลอด", "plod", "safe", "safe", "adjectives"),
        ("dangerous_a", "1F4A9", "อันตราย", "antarai", "dangerous", "dangerous", "adjectives"),
        ("zero_n", "0️⃣", "ศูนย์", "sun", "zero", "zéro", "numbers"),
        ("eleven_n", "1️⃣", "สิบเอ็ด", "sip et", "eleven", "onze", "numbers"),
        ("twelve_n", "2️⃣", "สิบสอง", "sip song", "twelve", "douze", "numbers"),
        ("twenty_n", "2️⃣", "ยี่สิบ", "yee sip", "twenty", "vingt", "numbers"),
        ("thirty_n", "3️⃣", "สามสิบ", "sam sip", "thirty", "trente", "numbers"),
        ("forty_n", "4️⃣", "สี่สิบ", "si sip", "forty", "quarante", "numbers"),
        ("fifty_n", "5️⃣", "ห้าสิบ", "ha sip", "fifty", "cinquante", "numbers"),
        ("sixty_n", "6️⃣", "หกสิบ", "hok sip", "sixty", "soixante", "numbers"),
        ("seventy_n", "7️⃣", "เจ็ดสิบ", "jet sip", "seventy", "soixante-dix", "numbers"),
        ("eighty_n", "8️⃣", "แปดสิบ", "paet sip", "eighty", "quatre-vingt", "numbers"),
        ("ninety_n", "9️⃣", "เก้าสิบ", "kao sip", "ninety", "quatre-vingt-dix", "numbers"),
        ("white_c", "⚪", "ขาว", "khao", "white", "blanc", "colors"),
        ("black_c", "⚫", "ดำ", "dam", "black", "noir", "colors"),
        ("gray_c", "🔘", "เทา", "thao", "gray", "gris", "colors"),
        ("brown_c", "🟤", "น้ำตาล", "nam taan", "brown", "marron", "colors"),
        ("gold_c", "🟨", "ทอง", "thong", "gold", "or", "colors"),
        ("silver_c", "⚪", "เงิน", "ngoen", "silver", "argent", "colors"),
        ("indigo_c", "🟦", "คราม", "khram", "indigo", "indigo", "colors"),
        ("turquoise_c", "🟦", "ฟ้าเข้ม", "faa khom", "turquoise", "turquoise", "colors"),
        ("maroon_c", "🟥", "แดงเข้ม", "daeng khom", "maroon", "maroon", "colors"),
        ("navy_c", "🟦", "กรมท่า", "krom tha", "navy", "bleu marine", "colors"),
        ("grandpa", "👴", "ปู่", "puu", "grandpa", "grandpa", "family"),
        ("grandma", "👵", "ย่า", "ya", "grandma", "grandma", "family"),
        ("uncle", "👨", "ลุง", "lung", "uncle", "uncle", "family"),
        ("aunt", "👩", "ป้า", "pa", "aunt", "tante", "family"),
        ("cousin", "👦", "ลูกพี่ลูกน้อง", "luk phi luk non", "cousin", "cousin", "family"),
        ("nephew", "👶", "หลานชาย", "laan chai", "nephew", "nephew", "family"),
        ("niece", "👧", "หลานสาว", "laan sao", "niece", "niece", "family"),
        ("teacher", "👨‍🏫", "ครู", "khru", "teacher", "professeur", "school"),
        ("student", "👨‍🎓", "นักเรียน", "naksian", "student", "étudiant", "school"),
        ("classroom", "🏫", "ห้องเรียน", "hong rian", "classroom", "classroom", "school"),
        ("question", "❓", "คำถาม", "kham taam", "question", "question", "adjectives"),
        ("answer", "❗", "คำตอบ", "kham tob", "answer", "réponse", "adjectives"),
        ("hello", "👋", "สวัสดี", "sawadee", "hello", "bonjour", "feelings"),
        ("goodbye", "👋", "ลาก่อน", "la kon", "goodbye", "au revoir", "feelings"),
        ("please", "🙏", "โปรด", "prode", "please", "s'il vous plaît", "feelings"),
        ("thank_you", "🙌", "ขอบคุณ", "khop khun", "thank you", "merci", "feelings"),
        ("sorry", "😔", "ขอโทษ", "kho thot", "sorry", "désolé", "feelings"),
        ("love", "❤️", "รัก", "rak", "love", "amour", "feelings"),
        ("fear", "😨", "กลัว", "klua", "fear", "peur", "feelings"),
        ("hope", "🌟", "หวัง", "wang", "hope", "espoir", "feelings"),
        ("proud", "😌", "ภูมิใจ", "phumi chai", "proud", "fier", "feelings"),
        ("shame", "😳", "อาย", "ai", "shame", "honte", "feelings"),
        ("doubt", "🤔", "สงสัย", "song sai", "doubt", "doute", "feelings"),
        ("surprise", "😲", "ประหลาดใจ", "pra lat chai", "surprise", "surprise", "feelings"),
        ("bored", "😐", "เบื่อ", "buer", "bored", "ennuyé", "feelings"),
        ("excited", "🎉", "ตื่นเต้น", "tuen tuen", "excited", "excité", "feelings"),
        ("jealous", "😒", "อิจฉา", "itcha", "jealous", "jaloux", "feelings"),
        ("lazy", "😴", "เกียจคร้าน", "kiat khan", "lazy", "paresseux", "adjectives"),
        ("honest", "👍", "สื่อสัตย์", "seu sat", "honest", "honnête", "adjectives"),
        ("rude", "😠", "ไม่สุภาพ", "nai thee", "rude", "impoli", "adjectives"),
        ("kind", "😇", "ใจดี", "chai di", "kind", "gentil", "adjectives"),
        ("mean", "😈", "ร้ายแรง", "rai raeng", "mean", "méchant", "adjectives"),
        ("clever", "🧠", "ฉลาด", "chalad", "clever", "intelligent", "adjectives"),
        ("silly", "🤪", "งี่เง่า", "ngee ngao", "silly", "bête", "adjectives"),
        ("brave", "💪", "กล้า", "klaa", "brave", "courageux", "adjectives"),
        ("afraid", "😨", "กลัว", "klua", "afraid", "peureux", "adjectives"),
        ("calm", "😌", "สงบ", "songop", "calm", "calme", "adjectives"),
        ("peaceful", "☮️", "สันติ", "santi", "peaceful", "paisible", "adjectives"),
        ("confused", "😕", "งง", "nong", "confused", "confus", "adjectives"),
        ("confident", "🦾", "มั่นใจ", "man chai", "confident", "confiant", "adjectives"),
        ("awkward", "😬", "อึดอัด", "ut at", "awkward", "maladroit", "adjectives"),
        ("perfect", "✨", "สมบูรณ์", "sombun", "perfect", "parfait", "adjectives"),
    ]
    return rawData.map { (id, hex, thai, rom, en, fr, cat) in
        Word(id: id, emoji: hexToEmoji(hex), thai: thai, romanization: rom, english: en, french: fr, category: cat)
    }
}()
